<?php 
$form = new RoleForm($formparams['event'], $data);
?>
<div class="panel panel-default role_list">
	<div class="panel-heading"><?= empty($page['title']) ? '添加角色' : $page['title']?></div>
	<div class="panel-body">
		<?=$form->beginForm(['action'=>$formparams['action']])?>
		<?=$form->renderFields()?>
		<?=$form->button('提交')?>
		<?=$form->endForm()?>
	</div>
</div>
<?php \Func\loadJsFile(null, ['depends'=>'\Assert\validate'])?>
