<div class="panel panel-default department_list">
	<div class="panel-heading">角色管理
		<a href="<?=\Func\url('/role/add')?>" class="pull-right">添加角色</a>
	</div>
	<div class="panel-body">
<?php if (count($roles)): ?>
		<table class="table table-striped">
			<tr>
				<th>ID</th>
				<th>角色名称</th>
				<th>部门名称</th>
				<th>操作</th>
			</tr>
<?php foreach ($roles as $key=>$row): ?>
			<tr>
				<td><?=$row['rid']?></td>
				<td><?=$row['name']?></td>
				<td><?=$row['dname']?></td>
				<td>
					<a href="<?=\Func\url('/role/edit/' . $row['rid'])?>">编辑</a>
					&nbsp;&nbsp;<a href="<?=\Func\url('/authority/allot/role/' . $row['rid'])?>">授权</a>
				</td>
			</tr>
<?php endforeach; ?>
		</table>
<?php else: ?>
		<div class="empty empty-content text-center">
			没有数据
		</div>
<?php endif; ?>
	</div>
</div>
