<?php

$form = new AdminiForm('login');
?>
<div class="login">
<div class="panel panel-default operator_list">
	<div class="panel-heading">管理员登录</div>
	<div class="panel-body">
		<?=$form->beginForm(['action'=>\Func\url('/public/login')])?>
		<?=$form->renderFields()?>
		<?=$form->button('提交')?>
		<?=$form->endForm()?>
	</div>
</div>
<?php \Func\loadJsFile(null, ['depends'=>'\Assert\validate'])?>
</div>
