<?php
if ($face and ($action != 'edit' || !$can_modify_actions['face'])):
?>
<div class="faceinfo">
<h5>面审信息<span class="pull-right"><?=date('Y/m/d', $face['addtime'])?></span></h5>
<hr/>
<table class="table">
	<tr>
		<td width=10%><label>信用报告说明</label></td>
		<td>
			<table class="table">
				<tr>
					<td width=15%></label>借款人及配偶负债</label></td>
					<td><?=$face['debt_amount']?></td>
				</tr>
				<tr>
					<td width=15%></label>证明方式</label></td>
					<td><?=$face['debt_prove']?></td>
				</tr>
				<tr>
					<td width=15%></label>每月还款金额</label></td>
					<td><?=$face['debt_month_repay']?></td>
				</tr>
				<tr>
					<td width=15%></label>逾期情况说明</label></td>
					<td><?=$face['debt_info']?></td>
				</tr>
				<tr>
					<td width=15%></label>车辆情况说明</label></td>
					<td><?=$face['debt_car_info']?></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td width=10%><label>基本情况说明</label></td>
		<td>
			<table class="table">
				<tr>
					<td width=15%></label>个人基本情况</label></td>
					<td><?=$face['info_base']?></td>
				</tr>
				<tr>
					<td width=15%></label>借款人及配偶收入情况</label></td>
					<td><?=$face['info_income']?></td>
				</tr>
<?php if (isset($car) and !empty($car)): ?>
				<tr>
					<td width=15%></label>车辆评估详情</label></td>
					<td>
<?php
echo "{$car['car_brand']} {$car['car_type']}", ' ';
echo \App\Config\Car::loan()[$car['car_loan']], ' ';
echo date('Y年',$car['car_register_date']), '购买 '; 
echo '开票价'.$car['car_price'], '万元', ' ';
echo '每月掉价：', $car['car_fall_price'], '元. ';
echo '评估：', $car['car_assess_price'], '万元.  ';
echo $car['car_assess_remark'];
?>
	&nbsp;<a href="/loan/info/<?=$car['uid']?>/car">详情</a>
<?php
if ($can_modify_actions['car']):
	echo '&nbsp;<a href="/loan/car/'.$user['uid'].'/edit">修改</a>';
endif;
?>
					</td>
				</tr>
<?php endif;?>
				<tr>
					<td width=15%></label>借款用途</label></td>
					<td><?=$face['use_info']?></td>
				</tr>
				<tr>
					<td width=15%></label>还款来源情况说明</label></td>
					<td><?=$face['repay_source']?></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td width=10%><label>面审资料</label></td>
		<td>
			<table class="table">
				<tr>
					<td colspan=2>
					<a href="/loan/info/<?=$face['uid']?>/face/files">查看</a>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
</div>
<?php
elseif ($can_modify_actions['face']):
	$this->partial('loan/partial/face');
endif;
?>
