<?php
function outputLi($text, $value)
{
	echo "<li><label>$text</label><span class='value'>$value</span></li>";
}
?>

<div class="detailInfo">
	<h5>客户信息</h5>
	<hr/>
	<div>
	<ul>
<?=outputLi('客户姓名', $user['realname'])?>
<?=outputLi('借款人电话', $user['mobile'])?>
<?=outputLi('身份证号', $user['idcard'])?>
<?=outputLi('配偶姓名', $user['spouse_name'])?>
<?=outputLi('配偶电话', $user['spouse_mobile'])?>
<?=outputLi('配偶身份证号', $user['spouse_idcard'])?>
	</ul>
	<div class="clear"></div>
	</div>
	<p>
		<label>居住地址</label>
		<span class="value">
			<span address-format="province"><?=$user['province']?></span>&nbsp;&nbsp;
			<span address-format="city" address-province="<?=$user['province']?>"><?=$user['city']?></span>&nbsp;&nbsp;
			<?=$user['address']?>
		</span>
	</p>
	<br/>
	<h5>贷款信息</h5>
	<hr/>
	<ul>
<?=outputLi('贷款金额', $loansketch['amount'].'万元')?>
<?=outputLi('贷款期限', $loansketch['deadline'].'个月')?>
<?=outputLi('还款方式', $loansketch['repay_method_text'])?>
<?=outputLi('贷款用途', $loansketch['use_type_text'])?>
	</ul>
	<div class="clear"></div>
	<p><label>贷款用途说明</label><value><?=$loansketch['use_type_info']?></value></p>
	<p><label>还款来源</label><value><?=$loansketch['repay_source']?></value></p>
</div>
