<div class="panel panel-default department_list">
	<div class="panel-heading">成员管理
		<a href="<?=\Func\url('operator/add')?>" class="pull-right">添加成员</a>
	</div>
	<div class="panel-body">
<?php if (count($operators)): ?>
		<table class="table table-striped">
			<tr>
				<th>ID</th>
				<th>用户名</th>
				<th>角色名称</th>
				<th>部门名称</th>
				<th>状态</th>
				<th>操作</th>
			</tr>
<?php foreach ($operators as $key=>$row): ?>
			<tr>
				<td><?=$row['oid']?></td>
				<td><?=$row['username']?></td>
				<td><?=$row['rname']?></td>
				<td><?=$row['dname']?></td>
				<td><?=$row['status_text']?></td>
				<td>
					<a href="<?=\Func\url('/operator/edit/' . $row['oid'])?>">编辑</a>
<?php if($row['is_freeze']): ?>
					<a ajax="true" ajax-action="<?=\Func\url('/operator/unfreeze/' . $row['oid'])?>">解冻</a>
<?php else: ?>
					<a ajax="true" ajax-action="<?=\Func\url('/operator/freeze/' . $row['oid'])?>">冻结</a>
<?php endif; ?>
				</td>
			</tr>
<?php endforeach; ?>
		</table>
<?php else: ?>
		<div class="empty empty-content text-center">
			没有数据
		</div>
<?php endif; ?>
	</div>
</div>
