drop table if exists `m_user`;
create table if not exists `m_user`(
	`uid` int auto_increment,
	`uname` varchar(15) not null,
	`password` char(32) not null,
	`paypwd` char(32) comment '支付密码',
	`umobile` varchar(15),
	`uemail` varchar(20),
	`avatar` varchar(100),
	`invite_uid` int unsigned default 1 comment '来源',
	`amount` decimal(12,2) default 0.00 comment '可用金额',
	`freeze` decimal(12,2) default 0.00 comment '冻结金额',
	`score` float(11,1) default 0.0,
	`avlscore` float(11,1) default 0.0 comment '可用积分',
	`vip` tinyint unsigned default 0 comment '会员等级',
	`realname` varchar(12),
	`birthday` int unsigned,
	`gender` tinyint unsigned default 0,
	`addtime` int unsigned not null,
	`addip` varchar(32) not null,
	`last_login_time` int unsigned,
	`last_login_ip` varchar(32),
	`login_count` int unsigned default 0,
	`login_error_count` tinyint unsigned default 0,
	`status` tinyint unsigned not null default 1,
	primary key(`uid`),
	unique key(`uname`),
	unique key(`umobile`),
	unique key(`uemail`)
)engine=InnoDB default charset=utf8 auto_increment=10000;
