<div class="modal fade" id="remitCertify">
	<div class="modal-dialog modal-small">
		<div class="modal-content">
			<div class="modal-header">
				<h5>上传汇款凭证</h5>
			</div>
			<div class="modal-body">

<form action="/finance/remit" enctype="multipart/form-data" method="POST" class="form-horizontal">
	<input type="hidden" name="lid" value="<?=$loan['lid']?>">
	<div class="form-group">
		<label class="col-lg-2 control-label">客户编号</label>
		<div class="col-lg-8">
			<label class="control-label"><?=$user['uid']?></label>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">汇款凭证</label>
		<div class="col-lg-3">
			<div class="file"><input type="file" name="file_remit_certify" id="file_remit_certify" fileupload-url='/public/upload' fileupload-elementid='file_remit_certify' fileupload-filename="file_remit_certify" fileupload-hiddeninput='remit_certify' fileupload-trigger='change' class="btn-fileupload"></div>
			<input type="hidden" name="remit_certify">
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label"></label>
		<div class="col-lg-6">
			<button type="submit" class="btn btn-primary">提交</button>
		</div>
	</div>
</form>

			</div>
			<div class="modal-footer"></div>
		</div>
	</div>
</div>
<?php
\Func\loadJsFile(null, ['depends'=>'\Assert\ajaxFileUpload'], APP_NAME);
?>
