<div class="modal fade" id="advise">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<h5>反馈</h5>
			</div>
			<div class="modal-body">

<form action="/rc/advise/<?=$user['uid']?>" method="post" class="form-horizontal">
	<input type="hidden" name="uid" value="<?=$user['uid']?>">
	<div class="form-group">
		<label class="col-lg-2 control-label">客户编号</label>
		<div class="col-lg-8">
			<label class="control-label"><?=$user['uid']?></label>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">修改位置</label>
		<div class="col-lg-3">
			<?=\Util\Html::select('advisetype', $advise_types)?>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">原因说明</label>
		<div class="col-lg-8">
			<?=\Util\Html::textarea('reason', ['class'=>'{required:1}'])?>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label"></label>
		<div class="col-lg-6">
			<button type="submit" class="btn btn-primary">提交</button>
		</div>
	</div>
</form>

			</div>
			<div class="modal-footer"></div>
		</div>
	</div>
</div>
<a class="advise" data-toggle="modal" data-target="#advise">反馈</a>
<?php \Func\loadJsFile('loan.js', ['depends'=>'\Assert\validate'], APP_NAME)?>
