<div class="modal fade" id="rcAgree">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<h5>案件同意 处理意见</h5>
			</div>
			<div class="modal-body">

<form action="/rc/deal" method="post" class="form-horizontal">
	<input type="hidden" name="uid" value="<?=$user['uid']?>">
	<input type="hidden" name="type" value="agree">
	<div class="form-group">
		<label class="col-lg-2 control-label">客户编号</label>
		<div class="col-lg-8">
			<label class="control-label"><?=$user['uid']?></label>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">金额</label>
		<div class="col-lg-3">
			<div class="input-group">
				<?=\Util\Html::input('amount', ['class'=>'{required:1}'], $face['amount'])?>
				<span class="input-group-addon">万元</span>
			</div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">期限</label>
		<div class="col-lg-3">
			<div class="input-group">
				<?=\Util\Html::select('deadline', \App\Config\Loan::deadlines(), [], $face['deadline'])?>
				<span class="input-group-addon">月</span>
			</div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">利率</label>
		<div class="col-lg-3">
			<div class="input-group">
				<?=\Util\Html::input('apr', ['class'=>'{required:1}'], $face['apr'])?>
				<span class="input-group-addon">%</span>
			</div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">还款方式</label>
		<div class="col-lg-3">
			<?=\Util\Html::select('repay_method', \App\Config\Loan::repayMethod(), [], $face['repay_method'])?>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">同意理由</label>
		<div class="col-lg-8">
			<?=\Util\Html::textarea('reason')?>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">补充说明</label>
		<div class="col-lg-8">
			<?=\Util\Html::textarea('remark')?>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label"></label>
		<div class="col-lg-6">
			<button type="submit" class="btn btn-primary">提交</button>
		</div>
	</div>
</form>

			</div>
			<div class="modal-footer"></div>
		</div>
	</div>
</div>
