<div class="modal fade" id="rcRefuse">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<h5>案件拒绝 处理意见</h5>
			</div>
			<div class="modal-body">

<form action="/rc/deal" method="post" class="form-horizontal">
	<input type="hidden" name="uid" value="<?=$user['uid']?>">
	<input type="hidden" name="type" value="refuse">
	<div class="form-group">
		<label class="col-lg-2 control-label">客户编号</label>
		<div class="col-lg-8">
			<label class="control-label"><?=$user['uid']?></label>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">拒绝理由</label>
		<div class="col-lg-8">
			<?=\Util\Html::textarea('reason', ['class'=>'{required:1, minlength:10}'])?>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">补充说明</label>
		<div class="col-lg-8">
			<?=\Util\Html::textarea('remark')?>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label"></label>
		<div class="col-lg-6">
			<button type="submit" class="btn btn-primary">提交</button>
		</div>
	</div>
</form>

			</div>
			<div class="modal-footer"></div>
		</div>
	</div>
</div>
