<div class="repay-list">
<h5>还款记录</h5>
<hr/>
<?php if ($repayList):?>
	<table class="table table-striped">
		<tr>
			<th>期数</th>
			<th>还款金额 (元)</th>
			<th>还款时间</th>
			<th>状态</th>
			<th>操作</th>
		</tr>
<?php foreach ($repayList as $row): ?>
		<tr>
		<td><?=$row['no']?></td>
		<td><?=$row['amount']?></td>
		<td><?=$row['date_text']?></td>
		<td><?=$row['status_text']?></td>
		<td>
<?php if (!$row['date']): ?>
<a class="repay" href="javascript:void(0)" repay-uid="<?=$detail['uid']?>" repay-no="<?=$row['no']?>" repay-amount="<?=$row['amount']?>" repay-id="<?=$row['id']?>">还款</a>
<?php endif; ?>
		</td>
		</tr>
<?php endforeach; ?>
	</table>
<?php else:?>
	<div class="empty empty-content text-center">没有还款记录</div>
<?php endif;?>
</div>
<?php 
if ($detail['return_num'] < $detail['deadline']):
	$bodyPartial = 'afterloan/footerBar';
endif;

$this->partial('afterloan/modal/repay');
\Func\loadJsFile('afterloan', ['depends'=>'\Assert\App'], APP_NAME);
?>
