<header>
	<div class="header">
		<div class="navbar-header">
			  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-header-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			  </button>
		</div>
		<div class="collapse navbar-collapse navbar-header-collapse">
			<!--
			<ul class="nav pull-left branchinfo">
			</ul>
			-->
<?php
$quicklinks = (new App())->getQuickLinks();
if (!empty($quicklinks)):
?>
		<ul class="nav navbar-nav pull-left quicklinks">	
<?php
	foreach ($quicklinks as $link): 
?>
			<li><a href="<?=$link['url']?>"><?=$link['text']?></a></li>
<?php
	endforeach;
?>
		</ul>	
<?php
endif;
?>
		<ul class="nav navbar-nav pull-right">	
			<li><?=$_operator['bname']?>&nbsp;&nbsp;<a href="<?=\Func\url('/public/logout')?>">( <?=$_operator['username']?> ) &nbsp; 退出</a></li>
		</ul>
		</div>
	</div>
</header>
