<nav>
	<ul class="pagination">
<?php
	if ($now == 1):
?>
		<li class="disabled"><a href="#">&laquo;</a></li>
<?php
	else:
?>
		<li class="disabled"><a href="<?=\Util\Link::pageLink($now-1)?>">&laquo;</a></li>
<?php
	endif;
	foreach ($list as $p):
		$active = $now == $p ? 'active' : '';
?>
	<li class="<?=$active?>"><a href="<?=\Util\Link::pageLink($p)?>"><?=$p?></a></li>
<?php
	endforeach;
	if ($now == $total):
?>
		<li class="disabled"><a href="#">&raquo;</a></li>
<?php
	else:
?>
		<li><a href="<?=\Util\Link::pageLink($now+1)?>">&raquo;</a></li>
<?php
	endif;
?>
	</ul>
</nav>
