<?php
$menus = Menu::all(false);
//$menus = Menu::tree((new App())->filterMenus($menus));
$menus = Menu::tree($menus);
?>
	<ul class="menus">
<?php
foreach ($menus as $key=>$menu):
?>
<li class="menu">
	<h5><?=$menu['name']?></h5>
<?php if ($menu['children']): ?>
	<ul class="menus_children">
<?php foreach ($menu['children'] as $k=>$child):
		$active = ($_params['controller'] == $child['controller']) ? ' active ' : '';
?>
		<li class="<?=$active?>"><a href="<?=$child['url']?>"><?=$child['name']?></a></li>
<?php endforeach; ?>
	</ul>
<?php endif; ?>
</li>
<?php
endforeach;
?>
	</ul>

