<?php
$heads['title'] = '贷款申请';
$form = new ModelForm();
?>
<div class="loan-apply">
<?=$form->beginForm(['action'=>\Func\url('/loan/apply/'.$uid.'')])?>
	<h5>客户信息</h5>
	<hr>
	<div class="form-group">
		<label class="col-lg-2 control-label">客户姓名</label>
		<div class="col-lg-3">
		<input type="text" name="realname" value="<?=$realname?>" class="form-control {required:1, ch:1}"> 
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">身份证号</label>
		<div class="col-lg-3">
		<input type="text" name="idcard" value="<?=$idcard?>" class="form-control {required:1, regex:'^[\\dxX]{16,18}$'}"> 
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">户口所在地</label>
		<div class="col-lg-7">
		<div cascaded-data="address" address-province="<?=$idcard_province?>" address-city="<?=$idcard_city?>" cascaded-fields="idcard_province#idcard_city"></div>	
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">居住地</label>
		<div class="col-lg-7">
			<div cascaded-data="address" address-province="<?=$province?>" address-city="<?=$city?>" cascaded-fields="province#city"></div>	
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">居住地址</label>
		<div class="col-lg-7">
		<input type="text" name="address" value="<?=$address?>" class="form-control {required:1, minlength:6, maxlength:50}"> 
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">联系方式</label>
		<div class="col-lg-3">
		<input type="text" name="mobile" value="<?=$mobile?>" class="form-control {required:1, regex:'^([\\d]{11};?)+$'}"> 
		</div>
		<div class="col-lg-2 remark">多个用分号 ';' 分隔</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">是否已婚</label>
		<div class="col-lg-3">
			<div class="radio">
				<?=\Util\Html::radio('marriage', [0=>'否', 1=>'是'], isset($marriage) ? $marriage : 0)?>
			</div>
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div id="marriageInfo" class="hide">
	<div class="form-group">
		<label class="col-lg-2 control-label">配偶姓名</label>
		<div class="col-lg-3">
		<input type="text" name="spouse_name" class="form-control" value="<?=$spouse_name?>"> 
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">配偶联系电话</label>
		<div class="col-lg-3">
		<input type="text" name="spouse_mobile" class="form-control" value="<?=$spouse_mobile?>"> 
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">配偶身份证号</label>
		<div class="col-lg-3">
		<input value="<?=$spouse_idcard?>" type="text" name="spouse_idcard" class="form-control {regex:'^([\\dxX]{16,18})?$'}"> 
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">配偶情况说明</label>
		<div class="col-lg-7">
			<?=\Util\Html::textarea('spouse_info', null, $spouse_info)?>
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">配偶签署担保函</label>
		<div class="col-lg-3">
			<div class="radio">
				<?=\Util\Html::radio('spouse_assure', [0=>'不愿意', 1=>'愿意'], isset($spouse_assure) ? $spouse_assure : 0)?>
			</div>
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">有无子女</label>
		<div class="col-lg-3">
			<div class="radio">
				<?=\Util\Html::radio('have_child', [0=>'无', 1=>'有'], isset($have_child) ? $have_child : 0)?>
			</div>
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">子女情况说明</label>
		<div class="col-lg-7">
			<?=\Util\Html::textarea('child_info', null, $child_info)?>
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">客户基本情况说明</label>
		<div class="col-lg-7">
			<?=\Util\Html::textarea('info', ['class'=>'{required:1, minlength:5, maxlength:200}'], $info)?>
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>

	<h5>贷款信息</h5>
	<hr>
	<div class="form-group">
		<label class="col-lg-2 control-label">贷款金额</label>
		<div class="col-lg-3">
			<div class="input-group">
			<input type="text" name="amount" class="form-control {required:1, number:1}" value="<?=$amount?>"> 
				<span class="input-group-addon">万元</span>
			</div>
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">贷款期限</label>
		<div class="col-lg-3">
			<div class="input-group">
				<?=\Util\Html::select('deadline', \App\Config\Loan::deadlines(), [], isset($deadline) ? $deadline : 6, false)?>
				<span class="input-group-addon">月</span>
			</div>
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">还款方式</label>
		<div class="col-lg-8">
			<div class="radio"><?=\Util\Html::radio('repay_method', \App\Config\Loan::repayMethod(), isset($repay_method) ? $repay_method : 'o')?></div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">贷款用途</label>
		<div class="col-lg-3">
			<?=\Util\Html::select('use_type', \App\Config\Loan::useType(), ['class'=>'{required:1}'], isset($use_type) ? $use_type : 0)?>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">贷款用途说明</label>
		<div class="col-lg-7">
			<?=\Util\Html::textarea('use_type_info', ['class'=>'{required:1, minlength:5, maxlength:200}'], $use_type_info)?>
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">还款来源</label>
		<div class="col-lg-7">
			<?=\Util\Html::textarea('repay_source', ['class'=>'{required:1, minlength:5, maxlength:200}'], isset($repay_source) ? $repay_source : 0)?>
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label"></label>
		<div class="col-lg-6">
			<button type="submit" class="btn btn-primary">提交</button>
		</div>
	</div>
<?=$form->endForm()?>
<?php \Func\loadJsFile('loan.js', ['depends'=>'\Assert\validate'], APP_NAME)?>
<?php \Func\loadJsFile(null, ['depends'=>'\Assert\address'], APP_NAME)?>
</div>
