<?php
$heads['title'] = '贷款申请';
?>
<div class="col-lg-1"></div>
<div class="col-lg-10">
<form class="form-horizontal" method="post" action="/loan/apply">
	<h5>客户信息</h5>
	<hr>
	<div class="form-group">
		<label class="col-lg-2 control-label">客户姓名</label>
		<div class="col-lg-3">
			<input type="text" name="realname" class="form-control {required:1, ch:1}"> 
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">身份证号</label>
		<div class="col-lg-3">
			<input type="text" name="idcard" class="form-control {required:1, regex:'^[\\dxX]{16,18}$'}"> 
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">户口所在地</label>
		<div class="col-lg-7">
			<div cascaded-data="address" cascaded-fields="idcard_province#idcard_city"></div>	
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">居住地</label>
		<div class="col-lg-7">
			<div cascaded-data="address" cascaded-fields="province#city"></div>	
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">居住地址</label>
		<div class="col-lg-7">
			<input type="text" name="address" class="form-control {required:1, minlength:6, maxlength:50}"> 
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">联系方式</label>
		<div class="col-lg-3">
			<input type="text" name="mobile" class="form-control {required:1, regex:'^([\\d]{11};?)+$'}"> 
		</div>
		<div class="col-lg-2 remark">多个用分号 ';' 分隔</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">是否已婚</label>
		<div class="col-lg-3">
			<div class="radio">
				<?=\Util\Html::radio('marriage', [0=>'否', 1=>'是'], 0)?>
			</div>
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div id="marriageInfo" class="hide">
	<div class="form-group">
		<label class="col-lg-2 control-label">配偶姓名</label>
		<div class="col-lg-3">
			<input type="text" name="spouse_name" class="form-control"> 
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">配偶身份证号</label>
		<div class="col-lg-3">
			<input type="text" name="spouse_idcard" class="form-control"> 
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">配偶情况说明</label>
		<div class="col-lg-7">
			<?=\Util\Html::textarea('spouse_info')?>
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">配偶签署担保函</label>
		<div class="col-lg-3">
			<div class="radio">
				<?=\Util\Html::radio('spouse_assure', [0=>'不愿意', 1=>'愿意'], 0)?>
			</div>
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">有无子女</label>
		<div class="col-lg-3">
			<div class="radio">
				<?=\Util\Html::radio('have_child', [0=>'无', 1=>'有'], 0)?>
			</div>
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">子女情况说明</label>
		<div class="col-lg-7">
			<?=\Util\Html::textarea('child_info')?>
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">客户基本情况说明</label>
		<div class="col-lg-7">
			<?=\Util\Html::textarea('info', ['class'=>'{required:1, minlength:5, maxlength:200}'])?>
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>

	<h5>贷款信息</h5>
	<hr>
	<div class="form-group">
		<label class="col-lg-2 control-label">贷款金额</label>
		<div class="col-lg-3">
			<div class="input-group">
				<input type="text" name="amount" class="form-control {required:1, number:1}"> 
				<span class="input-group-addon">万元</span>
			</div>
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">贷款期限</label>
		<div class="col-lg-3">
			<div class="input-group">
				<?=\Util\Html::select('deadline', \App\Config::deadlines(), [], 6, false)?>
				<span class="input-group-addon">月</span>
			</div>
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">还款方式</label>
		<div class="col-lg-8">
			<div class="radio"><?=\Util\Html::radio('repay_method', \App\Config::repayMethod(), 'o')?></div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">贷款用途</label>
		<div class="col-lg-3">
			<?=\Util\Html::select('use_type', \App\Config::loanUsetype(), ['class'=>'{required:1}'])?>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">贷款用途说明</label>
		<div class="col-lg-7">
			<?=\Util\Html::textarea('use_type_info', ['class'=>'{required:1, minlength:5, maxlength:200}'])?>
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">还款来源</label>
		<div class="col-lg-7">
			<?=\Util\Html::textarea('repay_source', ['class'=>'{required:1, minlength:5, maxlength:200}'])?>
		</div>
		<div class="col-lg-3 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label"></label>
		<div class="col-lg-6">
			<button type="submit" class="btn btn-primary">提交</button>
		</div>
	</div>
</form>
<?php \Func\loadJsFile('loan.js', ['depends'=>'\Assert\validate'], APP_NAME)?>
<?php \Func\loadJsFile(null, ['depends'=>'\Assert\address'], APP_NAME)?>
</div>
