<?php
switch ($action)
{
case 'face':
	$title = '面审';
	break;
case 'visit':
	$title = '实地外访';
	break;
case 'car':
	$title = '车评';
	break;
case 'reface':
	$title = '复审';
	break;
default:
	$title = '详情';
	break;
}
$heads['title'] = $title;

if ($can_modify_actions['apply']) {
	echo '<a href="/loan/apply/'.$user['uid'].'" class="advise">修改</a>';
}
?>
<div class="loan-detail">
<?php

if ($advises) {
	$this->partial('advise/list');
}

//客户信息展示 
$this->partial('loan/info/user');
//贷款资料
$this->partial('loan/info/loansketch');

$this->partial('loan/info/face');
$this->partial('loan/info/visit');
$this->partial('loan/info/reface');

if (isset($adviseTypes) and is_array($adviseTypes)) {
	$this->partial('loan/modal/advise');
}

\Func\loadJsFile(null, ['depends'=>'\Assert\address'], APP_NAME);
?>
</div>
