<?php
switch ($action)
{
case 'face':
	$title = '面审';
	break;
case 'visit':
	$title = '实地外访';
	break;
case 'car':
	$title = '车评';
	break;
case 'reface':
	$title = '复审';
	break;
default:
	$title = '详情';
	break;
}
$heads['title'] = $title;

?>
<div class="loan-detail">
<?php
//客户信息展示 
$this->partial('loan/partial/baseinfo');

//面审信息
if (isset($faceinfo))
{
	if (empty($faceinfo))
	{
		if ($operate['face'] and \App\LoanStatus::needFace($detailInfo['status']))
			$this->partial('loan/partial/face');
	}
	else
	{
		$this->partial('loan/partial/faceinfo');
	}
}

//实地外访信息
if (isset($visitinfo))
{
	if (empty($visitinfo))
	{
		if ($operate['visit'] and \App\LoanStatus::needVisit($detailInfo['status']))
			$this->partial('loan/partial/visit');
	}
	else
	{
		$this->partial('loan/partial/visitinfo');
	}
}

//车评
if (isset($carinfo))
{
	if (empty($carinfo) and $operate['car'] and \App\LoanStatus::needCarAssess($detailInfo['status']))
	{
		$this->partial('loan/partial/carassess');
	}
}

//复审
if (isset($refaceinfo))
{
	if (empty($refaceinfo) and $operate['reface'] and \App\LoanStatus::needReface($detailInfo['status']))
	{
		$this->partial('loan/partial/reface');
	}
	else if (!empty($refaceinfo))
	{
		$this->partial('loan/partial/refaceinfo');
	}
}

\Func\loadJsFile(null, ['depends'=>'\Assert\address'], APP_NAME);
?>
</div>
