<?php
$heads['title'] = '贷款申请';
$form = new ModelForm();
?>
<div class="loan-apply">
<?=$form->beginForm(['action'=>\Func\url('/loan/upload/'.$type.'/'.$uid)])?>
	<h5><?=$label?></h5>
	<hr>
	<div class="form-group">
		<label class="col-lg-2 control-label">选择文件</label>
		<div class="col-lg-3">
			<input type="file" name="file" class="input-text" id="file"> 
		</div>
		<div class="col-lg-3 help-block">
		</div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label"></label>
		<div class="col-lg-3">
			<button class="btn btn-primary btn-fileupload" fileupload-url="<?=\Func\url('/loan/upload/'.$type.'/'.$uid)?>" fileupload-elementid="file" fileupload-filename="file" fileupload-alert="true" fileupload-reload="true" type="submit">上传</button>
		</div>
	</div>
<?=$form->endForm()?>
<?php \Func\loadJsFile(null, ['depends'=>'\Assert\ajaxfileupload'], APP_NAME)?>
	<div class="files-box">
<?php 
foreach ($files as $file):
	if ($file['is_img']):
		echo '<img src="'.$file['path'].'" class="img">';
	endif;
endforeach;
?>
	</div>
</div>
