<?php
function outputLi($text, $value)
{
	echo "<li><label>$text</label><span class='value'>$value</span></li>";
}
?>

<div class="detailInfo">
	<h5>客户信息</h5>
	<hr/>
	<div>
	<ul>
<?=outputLi('客户编号', $user['uid'])?>
<?=outputLi('客户姓名', $user['realname'])?>
<?=outputLi('联系方式', $user['mobile'])?>
<?=outputLi('身份证号', $user['idcard'])?>
	</ul>
	<div class="clear"></div>
	</div>
	<p>
		<label>居住地址</label>
		<span class="value">
			<span address-format="province"><?=$user['province']?></span>&nbsp;&nbsp;
			<span address-format="city" address-province="<?=$user['province']?>"><?=$user['city']?></span>&nbsp;&nbsp;
			<?=$user['address']?>
		</span>
	</p>
</div>
