<div class="faceinfo">
<h5>面审信息<span class="pull-right"><?=date('Y/m/d', $face['addtime'])?></span></h5>
<hr/>
<table class="table">
	<tr>
		<td width=10%><label>信用报告说明</label></td>
		<td>
			<table class="table">
				<tr>
					<td width=15%></label>负债总额</label></td>
					<td><?=$face['debt_amount']?></td>
				</tr>
				<tr>
					<td width=15%></label>证明方式</label></td>
					<td><?=$face['debt_prove']?></td>
				</tr>
				<tr>
					<td width=15%></label>每月还款金额</label></td>
					<td><?=$face['debt_month_repay']?></td>
				</tr>
				<tr>
					<td width=15%></label>逾期情况说明</label></td>
					<td><?=$face['debt_info']?></td>
				</tr>
				<tr>
					<td width=15%></label>按揭车还款情况</label></td>
					<td><?=$face['debt_car_info']?></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td width=10%><label>基本情况说明</label></td>
		<td>
			<table class="table">
				<tr>
					<td width=15%></label>个人基本情况</label></td>
					<td><?=$face['info_base']?></td>
				</tr>
				<tr>
					<td width=15%></label>个人收入情况</label></td>
					<td><?=$face['info_income']?></td>
				</tr>
<?php if (isset($carinfo) and !empty($carinfo)): ?>
				<tr>
					<td width=15%></label>车辆评估详情</label></td>
					<td>
<?php
echo "{$carinfo['car_brand']} {$carinfo['car_type']}", ' ';
echo \App\Config\Car::loan()[$carinfo['car_loan']], ' ';
echo '开票价'.$carinfo['car_price'], '万元', ' ';
echo date('Y年',$carinfo['car_buytime']), '购买 '; 
echo '外观：', \App\Config\Car::appearance()[$carinfo['car_appearance']], '. ';
echo '内观：', \App\Config\Car::inappearance()[$carinfo['car_inappearance']], '. ';
echo '交通事故：', $carinfo['car_accident_info'], '. ';
echo '每月掉价：', $carinfo['car_fall_price'], '元. ';
echo '评估：', $carinfo['car_assess_price'], '万元.  ';
echo $carinfo['car_remark'];
?>
					</td>
				</tr>
<?php endif;?>
				<tr>
					<td width=15%></label>借款用途核实</label></td>
					<td><?=$face['use_info']?></td>
				</tr>
				<tr>
					<td width=15%></label>还款来源核实</label></td>
					<td><?=$face['repay_source']?></td>
				</tr>
			</table>
		</td>
	</tr>
</table>
</div>
