<?php
function outputLi($text, $value)
{
	echo "<li><label>$text</label><span class='value'>$value</span></li>";
}
?>
<div class="afterloan-detail">
	<div class="detail">
	<h5>贷款详情</h5>
	<hr/>
	<ul class="clearfix">
<?=outputLi('客户编号', $detail['uid'])?>
<?=outputLi('贷款金额', $detail['amount'].'万元')?>
<?=outputLi('贷款方式', $detail['loan_type_text'])?>
<?=outputLi('还款方式', $detail['repay_method_text'])?>
<?=outputLi('贷款期数', $detail['deadline'].'期')?>
<?=outputLi('已还期数', $detail['return_num'].'期')?>
<?=outputLi('贷款时间', $detail['begintime'])?>
	</ul>
	</div>
	<?=$this->partial('afterloan/partial/repaylist')?>
</div>
