<?php
$heads['title'] = '贷款列表';
?>

<div class="loan-list">
	<form class="search row" action="<?=\Func\url('/afterloan/list')?>" method="get">
		<div class="col-lg-3">
			<div class="input-group">
				<?=\Util\Html::input('keyword', ['placeholder'=>'请输入客户编号或姓名'], $_REQUEST['keyword'])?>
				<span class="input-group-addon btn-search">搜索</span>
			</div>
		</div>
		<div class="col-lg-1"><div class="row"><a class="btn btn-link" href="/afterloan/list">清除</a></div></div>
	</form>
	<br/>
<?php
if (!empty($list)):
?>
<table class="table table-striped">
	<tr>
		<th>客户编号</th>
		<th>客户姓名</th>
		<th>联系方式</th>
		<th>贷款方式</th>
		<th>贷款金额 (万)</th>
		<th>还款方式</th>
		<th>贷款期数</th>
		<th>已还期数</th>
		<th>上一次还款日</th>
		<th>逾期天数</th>
		<th>操作</th>
	</tr>
<?php
	foreach ($list as $row):
?>

	<tr>
		<td><?=$row['uid']?></td>
		<td><?=$row['realname']?></td>
		<td><?=$row['mobile']?></td>
		<td><?=$row['loan_type_text']?></td>
		<td><?=$row['amount']?></td>
		<td><?=$row['repay_method_text']?></td>
		<td><?=$row['deadline']?>期</td>
		<td><?=$row['return_num']?>期</td>
		<td>
<?php 
if ($row['return_num']):
	echo date('Y-m-d', $row['last_repay_time']);
endif;
?>
		</td>
		<td><?=$row['overdue_days']?></td>
		<td>
			<a href="/afterloan/detail/<?=$row['uid']?>">详情</a>
		</td>
	</tr>

<?php
	endforeach;
?>
</table>	
<?php
		$this->partial('common/page', $page);
else:
?>
		<div class="empty empty-content text-center">
			没有数据
		</div>
<?php
endif;
?>

</div>
