<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8"/>
	<link rel="stylesheet" href="/public/css/lib/bootstrap.min.css">
	<link rel="stylesheet" href="/public/css/site.css">
	<title><?= isset($heads['title']) ? $heads['title'] . ' - ' : ''?>贷款系统</title>
</head>
<body>

<?=$this->getContent()?>
	<?= $this->partial('common/footer') ?>

<?php
\Assert\app();
\Assert\output(null, true);
?>
</body>
</html>
