<?php
$heads['title'] = '合同签署';
?>
<div class="rc-detail">
<?php
//客户信息展示 
$this->partial('rc/partial/baseinfo');

$this->partial('rc/partial/loaninfo');

$this->partial('rc/partial/rcinfo');

$this->partial('supervisor/partial/contract');

$this->partial('gps/partial/gps');

\Func\loadJsFile(null, ['depends'=>'\Assert\address'], APP_NAME);

$bodyPartial = ['afterrc/footerBar', [
		'auth_actions'=>$auth_actions,
		'contract'	=>	$loan['contract'],
		'gps'	=>	$loan['gps'],
		'carkey'	=>	$loan['car_key'],
		'pledgenotary'	=>	$loan['pledge_notary']
	]];
?>
</div>
