<div class="panel panel-default department_list">
	<div class="panel-heading">管理员账号
		<a href="<?=\Func\url('admini/add')?>" class="pull-right">添加</a>
	</div>
	<div class="panel-body">
<?php if (count($list)): ?>
		<table class="table table-striped">
			<tr>
				<th>用户名</th>
				<th>所属门店</th>
				<th>操作</th>
			</tr>
<?php foreach ($list as $key=>$row): ?>
			<tr>
				<td><?=$row['username']?></td>
				<td><?=$row['bname']?></td>
				<td><a href="<?=\Func\url('/admini/edit/' . $row['aid'])?>">编辑</a></td>
			</tr>
<?php endforeach; ?>
		</table>
<?php else: ?>
		<div class="empty empty-content text-center">
			没有数据
		</div>
<?php endif; ?>
	</div>
</div>
