<div class="panel panel-default authority_list">
	<div class="panel-heading"><?= empty($page['title']) ? '角色授权' : $page['title']?></div>
	<div class="panel-body">
		<form action="<?=$formparams['action']?>" class="form-horizontal" method="post">	
		<input type="hidden" name="type" value="<?=$formparams['type']?>">
		<input type="hidden" name="id" value="<?=$formparams['id']?>">
		<div class="form-group">
			<label class="col-lg-1 control-label">角色</label>
			<div class="col-lg-3">
				<label class="control-label plain"><?= ($formparams['type'] == 'role') ? $info['name'] : $info['rname'];?></label>
			</div>
		</div>
		<div class="form-group">
			<label class="col-lg-1 control-label">部门</label>
			<div class="col-lg-3">
				<label class="control-label plain"><?=$info['dname']?></label>
			</div>
		</div>
		<div class="form-group">
			<label class="col-lg-1 control-label">权限</label>
			<div class="col-lg-11">
<table class="table table-striped">
	<tr>
		<th width=15%>APP</th>
		<th width=15%>模块</th>
		<th width=70%>方法</th>
	</tr>
<?php 
$auth = [];
if (!empty($info['auth']))
	$auth = unserialize($info['auth']);

	foreach ($authorities as $app=>$authority):
?>
	<tr>
		<!--APP-->
		<td><label><input name="app" value="<?=$app?>" type="checkbox">&nbsp;<?=App::getTextByAppname($app)?></label></td>
		<td colspan=2>
<?php
		foreach ($authority as $key=>$controller):
?>
			<!--模块-->
			<table width=100%>
				<tr>
					<td width=18%>
						<label>
							<input type="checkbox" app="<?=$app?>" name="controller" value="<?=$key?>">
							&nbsp;<?=$controller['name']?>
						</label>	
					</td>
					<td>
						<!--模块方法-->
						<ul>
<?php
			if (is_array($controller['authorities'])):
				$i = 0;
				foreach ($controller['authorities'] as $action=>$label):
					$checked = Authority::actionExist($auth, $key, $action, $app) ? 'checked' : '';
?>
							<li style="width:20%;" class="pull-left"><input app="<?=$app?>" controller="<?=$key?>" <?=$checked?> type="checkbox" name="action" value="<?=$action?>">&nbsp;<label><?=$label?><label></li>
<?php
				endforeach;
			endif;
?>
						</ul>
					</td>
				</tr>	
			</table>
<?php
		endforeach;
?>
		</td>
		<td></td>
	</tr>	
<?php
	endforeach;
?>	
</table>
			</div>	
		</div>
		<div class="form-group">
			<label class="col-lg-1 control-label"></label>
			<div class="col-lg-11">
				<p class="text-primary">注：权限参考标准以模块的方法勾选为准 , APP和模块的勾选框仅是辅助勾选框 ! </p>
			</div>
		</div>
		<div class="form-group">
			<label class="col-lg-1 control-label"></label>
			<div class="col-lg-3">
				<button type="submit" class="btn btn-primary">提交</button>
			</div>
		</div>
		</form>
	</div>
</div>
<?php \Func\loadJsFile('authority.js')?>
