<div class="panel panel-default department_list">
	<div class="panel-heading">权限列表
		<a href="<?=\Func\url('/authority/add')?>" class="pull-right">添加权限</a>
	</div>
	<div class="panel-body">
<?php if (count($roles)): ?>
		<table class="table table-striped">
			<tr>
				<th>ID</th>
				<th>App</th>
				<th>Controller</th>
				<th>Action</th>
			</tr>
<?php foreach ($roles as $key=>$row): ?>
			<tr>
				<td><?=$row['rid']?></td>
				<td><?=$row['name']?></td>
				<td><?=$row['dname']?></td>
				<td><a href="<?=\Func\url('/role/edit/' . $row['rid'])?>">编辑</a></td>
			</tr>
<?php endforeach; ?>
		</table>
<?php else: ?>
		<div class="empty empty-content text-center">
			没有数据
		</div>
<?php endif; ?>
	</div>
</div>
