<?php
$heads['title'] = '详情';
?>
<div class="loan-detail">
<?php
if ($advises) {
	$this->partial('advise/list');
}
//客户信息展示 
$this->partial('loan/info/user');

$this->partial('loan/info/loansketch');

$this->partial('loan/info/face');
$this->partial('loan/info/visit');
$this->partial('loan/info/reface');

\Func\loadJsFile(null, ['depends'=>'\Assert\address'], APP_NAME);

if (isset($advise_types) and is_array($advise_types)) {
	$this->partial('rc/modal/advise');
}
$bodyPartial = 'rc/footerBar';
?>
</div>
