<?php
$heads['title'] = '案件列表';
?>

<div class="loan-list">
	<form class="search row" action="<?=\Func\url('/rc/list')?>" method="get">
		<div class="col-lg-2">
			<?=\Util\Html::select('bid', Branch::options(), null, $_REQUEST['bid'])?>
		</div>
		<div class="col-lg-3">
			<?=\Util\Html::input('keyword', ['placeholder'=>'请输入客户编号或姓名'], $_REQUEST['keyword'])?>
		</div>
		<span class="btn btn-primary btn-search">
			搜索
		</span>
	</form>
	<br/>
<?php
if (!empty($list)):
?>
<table class="table table-striped">
	<tr>
		<th>客户编号</th>
		<th>贷款金额 (万)</th>
		<th>贷款期限</th>
		<th>还款方式</th>
		<th>贷款用途</th>
		<th>所属门店</th>
		<th>操作</th>
	</tr>
<?php
	foreach ($list as $row):
?>

	<tr>
		<td><?=$row['uid']?></td>
		<td><?=$row['amount']?></td>
		<td><?=$row['deadline'] . ($row['deadline'] == 'd' ? '天' : '个月')?></td>
		<td><?=$row['repay_method_text']?></td>
		<td><?=$row['use_type_text']?></td>
		<td><?=$row['bname']?></td>
		<td>
			<a href="/rc/detail/<?=$row['uid']?>">详情</a>
		</td>
	</tr>

<?php
	endforeach;
?>
</table>	
<?php
		$this->partial('common/page', $page);
else:
?>
		<div class="empty empty-content text-center">
			没有数据
		</div>
<?php
endif;
?>

</div>
