<?php 
$form = new DepartmentForm($formparams['event'], $data);
?>
<div class="panel panel-default department_list">
<div class="panel-heading"><?= empty($head['title']) ? '添加部门' : $head['title']?></div>
	<div class="panel-body">
		<?=$form->beginForm(['action'=>$formparams['action']])?>
		<?=$form->renderFields()?>
		<?=$form->button('提交', ['id'=>'submit_department_add'])?>
		<?=$form->endForm()?>
	</div>
</div>
<?php \Func\loadJsFile(null, ['depends'=>'\Assert\validate'])?>
