<?php 
$form = new DepartmentForm();
?>
<div class="panel panel-default department_list">
	<div class="panel-heading">添加部门</div>
	<div class="panel-body">
		<?=$form->beginForm(['action'=>\Func\url('/department/add')])?>
		<?=$form->renderFields()?>
		<?=$form->button('提交', ['id'=>'submit_department_add'])?>
		<?=$form->endForm()?>
	</div>
</div>
<?php \Func\loadJsFile(null, ['depends'=>'\Assert\validate'])?>
