<div class="modal fade" id="contractSign">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<h5>合同签署</h5>
			</div>
			<div class="modal-body">

<form action="/supervisor/sign" method="post" class="form-horizontal">
	<input type="hidden" name="uid" value="<?=$loan['uid']?>">
	<div class="form-group">
		<label class="col-lg-2 control-label">客户编号</label>
		<div class="col-lg-8">
			<label class="control-label"><?=$user['uid']?></label>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">合同签署</label>
		<div class="col-lg-3 disabled">
			<div class="checkbox"><?=\Util\Html::checkbox('contract', [1=>'已签署'], 1)?></div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">开户银行</label>
		<div class="col-lg-6">
			<?=\Util\Html::input('bank', ['class'=>'{required:1, minlength:10}'])?>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">银行卡号</label>
		<div class="col-lg-6">
			<?=\Util\Html::input('bank_card', ['class'=>'{regex:\'^[\\\\d]{10,20}$\'}'])?>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">确认卡号</label>
		<div class="col-lg-6">
			<?=\Util\Html::input('bank_card_confirm', ['class'=>'{required:1, equalTo:\'[name=bank_card]\'}'])?>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label"></label>
		<div class="col-lg-6">
			<button type="submit" class="btn btn-primary">提交</button>
		</div>
	</div>
</form>

			</div>
			<div class="modal-footer"></div>
		</div>
	</div>
</div>
