<div class="rc-deal">
	<h5>总部风控处理意见</h5>
	<hr/>
	<table style="width:80%">
		<tr><td width=25%><label>处理结果</label></td><td colspan=2><?=\App\LoanStatus::getStatusText($loan['status'])?></td></tr>	
<?php 
if ($loan['status'] == \App\LoanStatus::getStatusRcAgree()):
?>
<tr>
<td><label>批准金额：</label><value><?=$loan['amount']?>万元</value></td>
<td><label>批准期限：</label><value><?=$loan['deadline']?>个月</value></td>
<td><label>批准年利率：</label><value><?=$loan['apr']?>%</value></td>
</tr>
<?php
endif;
?>
		<tr><td><label>同意或拒绝的理由</label></td><td><?=$loan['reason']?></td></tr>	
		<tr><td><label>补充说明</label></td><td><?=$loan['remark']?></td></tr>	
	</table>
</div>
