<div class="modal fade" id="runConfirm">
	<div class="modal-dialog modal-small">
		<div class="modal-content">
			<div class="modal-header">
				<h5>确认放款</h5>
			</div>
			<div class="modal-body">

<form action="/run/confirm/<?=$loan['uid']?>" method="post" class="form-horizontal">
	<input type="hidden" name="uid" value="<?=$loan['uid']?>">
	<div class="form-group">
		<label class="col-lg-2 control-label">客户编号</label>
		<div class="col-lg-8">
			<label class="control-label"><?=$user['uid']?></label>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label"></label>
		<div class="col-lg-6">
			<button type="submit" class="btn btn-primary">提交</button>
		</div>
	</div>
</form>

			</div>
			<div class="modal-footer"></div>
		</div>
	</div>
</div>
