<?php 
$form = new BranchForm();
?>
<div class="panel panel-default branch_list">
<div class="panel-heading"><?= (isset($formparams['event']) and $formparams['event'] == 'edit') ? '编辑门店' : '添加门店'?></div>
	<div class="panel-body">
		<?=$form->beginForm(['action'=>$formparams['action']])?>
<?php 
	if (isset($info)):
?>
<input type="hidden" name="bid" value="<?=$info['bid']?>">
<?php
	endif;
?>
		<div class="form-group">
			<label class="col-lg-2 control-label">门店名称</label>
			<div class="col-lg-3">
			<input type="text" name="name" <?php if ($info['name']):?> value="<?=$info['name']?>" <?php endif;?> class="form-control {required:1}"> 
			</div>
			<div class="col-lg-3 help-block"></div>
		</div>
		<div class="form-group">
			<label class="col-lg-2 control-label">地区</label>
			<div class="col-lg-7">
				<div cascaded-data="address" <?php if ($info['province']):?> address-province="<?=$info['province']?>" <?php endif;?> <?php if ($info['city']):?> address-city="<?=$info['city']?>" <?php endif;?>cascaded-fields="province#city"></div>	
			</div>
			<div class="col-lg-3 help-block"></div>
		</div>
		<?=$form->button('提交', ['id'=>'submit_branch_add'])?>
		<?=$form->endForm()?>
	</div>
</div>
<?php \Func\loadJsFile(null, ['depends'=>'\Assert\validate'])?>
<?php \Func\loadJsFile(null, ['depends'=>'\Assert\address'])?>
