<div class="panel panel-default branch_list">
	<div class="panel-heading">门店管理
		<a href="<?=\Func\url('/branch/add')?>" class="pull-right">添加门店</a>
	</div>
	<div class="panel-body">
<?php if (count($branches)): ?>
		<table class="table table-striped">
			<tr>
				<th>门店名称</th>
				<th>省份</th>
				<th>城市</th>
				<th>操作</th>
			</tr>
<?php foreach ($branches as $key=>$row): ?>
			<tr>
				<td><?=$row['name']?></td>
				<td address-format="province"><?=$row['province']?></td>
				<td address-format="city" address-province="<?=$row['province']?>"><?=$row['city']?></td>
				<td><a href="<?=\Func\url('branch/edit/'.$row['bid'])?>">编辑</a></td>
			</tr>
<?php endforeach; ?>
		</table>
<?php else: ?>
		<div class="empty empty-content text-center">
			没有数据
		</div>
<?php endif; ?>
	</div>
</div>
<?php \Func\loadJsFile(null, ['depends'=>'\Assert\address'])?>
