<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    	<meta charset="UTF-8" />
		<meta name="keywords" content="yii framework, tutorial, guide, version 1.1" />
	<meta name="description" content="A module is a self-contained software unit that consists of models, views, controllers and other supporting components. In many aspects, a module resembles to an application." />
    <link rel="shortcut icon" type="image/x-icon" href="http://static.yiiframework.com/favicon.ico" />
    <link rel="stylesheet" type="text/css" href="http://static.yiiframework.com/css/site-20130404102234.css" />

	<link title="Lives News for Yii Framework" rel="alternate" type="application/rss+xml" href="http://www.yiiframework.com/rss.xml/" />
	<title>Fundamentals: Module | The Definitive Guide to Yii | Yii PHP Framework</title>
	<link rel="search" type="application/opensearchdescription+xml" title="Yii API Search" href="/search-api.xml" />
	<link rel="search" type="application/opensearchdescription+xml" title="Yii Site Search" href="/search-site.xml" />
</head>

<body class="mac">
<div class="layout-main">

	<div class="layout-main-shortcuts">
		<div class="container_12">
            <a style="color:darkred;" href="https://github.com/yiisoft/yii2">Github</a> &middot;
            <a style="color:darkgreen;" href="https://twitter.com/yiiframework">Twitter</a> &middot;
            <a style="color:darkblue;" href="https://www.facebook.com/groups/yiitalk/">Facebook</a> &middot;
            <a href="/doc/guide/">Guide</a> &middot;
            <a href="/doc/api/">Class Reference</a> &middot;
            <a href="/doc-2.0/guide-index.html">Guide 2.0</a> &middot;
            <a href="/doc-2.0/index.html">API 2.0</a> &middot;
            <a href="/wiki/">Wiki</a> &middot;
            <a href="/extensions/">Extensions</a> &middot;
            <a href="/forum/">Forum</a> &middot;
			<a href="/chat/">Live Chat</a> &middot;
                            <a href="/login/">Login</a>            		</div>
	</div>

	<div class="layout-main-bg">
		<div class="layout-main-header">
			<div class="container_12">
				<div class="grid_4">
					<a class="logo" href="/"><img alt="Yii Logo" src="http://static.yiiframework.com/css/img/logo.png" title="Yii Framework" width="284" height="64" /></a>				</div>
				<div class="grid_8 omega">
					<div class="nav">
						<ul class="menu" id="yw0">
<li class="about"><a class="main" href="/about/">About</a>
<ul>
<li><a href="/about/">About Yii</a></li>
<li><a href="/features/">Features</a></li>
<li><a href="/performance/">Performance</a></li>
<li><a href="/license/">License</a></li>
<li class="last"><a href="/contact/">Contact Us</a></li>
</ul>
</li>
<li class="downloads"><a class="main" href="/download/">Downloads</a>
<ul>
<li><a href="/download/">Framework</a></li>
<li><a href="/extensions/">Extensions</a></li>
<li><a href="/demos/">Demos</a></li>
<li class="last"><a href="/logo/">Logo</a></li>
</ul>
</li>
<li class="documentation active"><a class="main" href="/doc/">Documentation</a>
<ul>
<li><a href="/tour/">Take the Tour</a></li>
<li class="active"><a href="/tutorials/">Tutorials</a></li>
<li><a href="/doc/api/">Class Reference</a></li>
<li><a href="/doc-2.0/guide-index.html">Guide 2.0</a></li>
<li><a href="/doc-2.0/index.html">Class Reference 2.0</a></li>
<li><a href="/wiki/">Wiki</a></li>
<li><a href="/screencasts/">Screencasts</a></li>
<li class="last"><a href="/resources/">Resources</a></li>
</ul>
</li>
<li class="development"><a class="main" href="https://github.com/yiisoft/yii/commits/master">Development</a>
<ul>
<li><a href="/contribute/">Contribute to Yii</a></li>
<li><a href="https://github.com/yiisoft/yii/commits/master">Latest Updates</a></li>
<li><a href="https://github.com/yiisoft/yii/issues/new">Report a Bug</a></li>
<li class="last"><a href="/security/">Report a Security Issue</a></li>
</ul>
</li>
<li class="community last"><a class="main" href="/community/">Community</a>
<ul>
<li><a href="/forum/">Forum</a></li>
<li><a href="/chat/">Live Chat</a></li>
<li><a href="/news/">News</a></li>
<li><a href="/user/halloffame/">Hall of Fame</a></li>
<li class="last"><a href="/badges/">Badges</a></li>
</ul>
</li>
</ul>						<div class="search">
							<form method="get" action="/search/">
								<div class="keyword">
	                                <input name="q" value="" />
									<a href="#" title="search" class="global-search">search</a>
								</div>
							</form>
						</div>
					</div>
				</div>
				<div class="clear"></div>
			</div>
		</div>

		<div class="container_12">
						<div class="grid_12">
												<div class="layout-main-submenu">
					<ul>
						<li class="main">Documentation</li>
												<li><a href="/tour/">Take the Tour</a></li>
												<li class="active"><a href="/tutorials/">Tutorials</a></li>
												<li><a href="/doc/api/">Class Reference</a></li>
												<li><a href="/doc-2.0/guide-index.html">Guide 2.0</a></li>
												<li><a href="/doc-2.0/index.html">Class Reference 2.0</a></li>
												<li><a href="/wiki/">Wiki</a></li>
												<li><a href="/screencasts/">Screencasts</a></li>
												<li><a href="/resources/">Resources</a></li>
											</ul>
				</div>
				
				
				
									<div class="layout-main-body">
						<div class="tutorial-view">
    <div class="grid_3 alpha">
        <div class="nav-toc">
    		<div class="title">The Definitive Guide to Yii</div>
    		<div class="langver">
	            <strong>Language &amp; version</strong>
	    		<div class="languages g-dropdown">
	    		<span>English<i></i></span>
<ul>
<li><a href="/doc/guide/1.1/de/basics.module">Deutsch</a></li>
<li><a href="/doc/guide/1.1/es/basics.module">Español</a></li>
<li><a href="/doc/guide/1.1/fr/basics.module">Français</a></li>
<li><a href="/doc/guide/1.1/he/basics.module">עִבְרִית</a></li>
<li><a href="/doc/guide/1.1/id/basics.module">Bahasa Indonesia</a></li>
<li><a href="/doc/guide/1.1/it/basics.module">Italiano</a></li>
<li><a href="/doc/guide/1.1/ja/basics.module">日本語</a></li>
<li><a href="/doc/guide/1.1/pl/basics.module">Polski</a></li>
<li><a href="/doc/guide/1.1/pt/basics.module">Português</a></li>
<li><a href="/doc/guide/1.1/pt_br/basics.module">Português brasileiro</a></li>
<li><a href="/doc/guide/1.1/ro/basics.module">România</a></li>
<li><a href="/doc/guide/1.1/ru/basics.module">Русский</a></li>
<li><a href="/doc/guide/1.1/sv/basics.module">Svenska</a></li>
<li><a href="/doc/guide/1.1/uk/basics.module">украї́нська</a></li>
<li><a href="/doc/guide/1.1/zh_cn/basics.module">简体中文</a></li>
</ul>
	    		</div>
				<div class="versions g-dropdown">
	    		<span>1.1<i></i></span>
<ul>
<li><a href="/doc/guide/1.0/en/basics.module">1.0</a></li>
</ul>
				</div>
				<div class="clear"></div>
			</div>
            <div class="widget-search-box">
    <form method="get" action="/search/">
        <strong>Search in this tutorial</strong>
		<input type="text" name="q" class="keyword g-text" />
        <input type="hidden" name="type" value="guide" />
        <input type="hidden" name="lang" value="en" />
        <input type="submit" value="Find" class="btn btn-info" />
	</form>
</div>
			<ul class="toc">
						    <li class="chapter"><strong>Getting Started</strong></li>
			    			        			            <li>
			                <a href="/doc/guide/1.1/en/index">Overview</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/changes">New Features</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/upgrade">Upgrading from 1.0 to 1.1</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/quickstart.what-is-yii">What is Yii</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/quickstart.installation">Installation</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/quickstart.apache-nginx-config">Apache and Nginx configurations</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/quickstart.first-app">Creating First Yii Application</a>			            </li>
			        			    						    <li class="chapter"><strong>Fundamentals</strong></li>
			    			        			            <li>
			                <a href="/doc/guide/1.1/en/basics.mvc">Model-View-Controller (MVC)</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/basics.entry">Entry Script</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/basics.application">Application</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/basics.controller">Controller</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/basics.model">Model</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/basics.view">View</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/basics.component">Component</a>			            </li>
			        			    			        			            <li class="active">
			                &raquo; Module &laquo;
			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/basics.namespace">Path Alias and Namespace</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/basics.convention">Conventions</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/basics.workflow">Development Workflow</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/basics.best-practices">Best MVC Practices</a>			            </li>
			        			    						    <li class="chapter"><strong>Working with Forms</strong></li>
			    			        			            <li>
			                <a href="/doc/guide/1.1/en/form.overview">Overview</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/form.model">Creating Model</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/form.action">Creating Action</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/form.view">Creating Form</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/form.table">Collecting Tabular Input</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/form.builder">Using Form Builder</a>			            </li>
			        			    						    <li class="chapter"><strong>Working with Databases</strong></li>
			    			        			            <li>
			                <a href="/doc/guide/1.1/en/database.overview">Overview</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/database.dao">Database Access Objects</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/database.query-builder">Query Builder</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/database.ar">Active Record</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/database.arr">Relational Active Record</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/database.migration">Database Migration</a>			            </li>
			        			    						    <li class="chapter"><strong>Caching</strong></li>
			    			        			            <li>
			                <a href="/doc/guide/1.1/en/caching.overview">Overview</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/caching.data">Data Caching</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/caching.fragment">Fragment Caching</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/caching.page">Page Caching</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/caching.dynamic">Dynamic Content</a>			            </li>
			        			    						    <li class="chapter"><strong>Extending Yii</strong></li>
			    			        			            <li>
			                <a href="/doc/guide/1.1/en/extension.overview">Overview</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/extension.use">Using Extensions</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/extension.create">Creating Extensions</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/extension.integration">Using 3rd-Party Libraries</a>			            </li>
			        			    						    <li class="chapter"><strong>Testing</strong></li>
			    			        			            <li>
			                <a href="/doc/guide/1.1/en/test.overview">Overview</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/test.fixture">Defining Fixtures</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/test.unit">Unit Testing</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/test.functional">Functional Testing</a>			            </li>
			        			    						    <li class="chapter"><strong>Special Topics</strong></li>
			    			        			            <li>
			                <a href="/doc/guide/1.1/en/topics.gii">Automatic Code Generation</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/topics.url">URL Management</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/topics.auth">Authentication and Authorization</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/topics.theming">Theming and Skin</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/topics.logging">Logging</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/topics.error">Error Handling</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/topics.webservice">Web Service</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/topics.i18n">Internationalization (I18N)</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/topics.prado">Alternative Template Syntax</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/topics.console">Console Applications</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/topics.security">Security</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/topics.performance">Performance Tuning</a>			            </li>
			        			    			        			            <li>
			                <a href="/doc/guide/1.1/en/quickstart.first-app-yiic">Code Generation using Command Line Tools (deprecated)</a>			            </li>
			        			    						</ul>
        </div>
    </div>
    <div class="grid_9 omega">
    	<div class="g-markdown"><h1 id="module">Module</h1>
<div class="google-ad" style="float:right;margin:0 0 1em 1em;">
<script type="text/javascript"><!--
google_ad_client = "ca-pub-3732587985864947";
google_ad_slot = "2830391674";
google_ad_width = 300;
google_ad_height = 250;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</div>
<div class="toc"><ol><li><a href="#creating-module">Creating Module</a></li>
<li><a href="#using-module">Using Module</a></li>
<li><a href="#nested-module">Nested Module</a></li></ol></div>


<p>A module is a self-contained software unit that consists of <a href="/doc/guide/1.1/en/basics.model">models</a>, <a href="/doc/guide/1.1/en/basics.view">views</a>, <a href="/doc/guide/1.1/en/basics.controller">controllers</a> and other supporting components. In many aspects, a module resembles to an <a href="/doc/guide/1.1/en/basics.application">application</a>. The main difference is that a module cannot be deployed alone and it must reside inside of an application. Users can access the controllers in a module like they do with normal application controllers.</p>

<p>Modules are useful in several scenarios. For a large-scale application, we may divide it into several modules, each being developed and maintained separately. Some commonly used features, such as user management, comment management, may be developed in terms of modules so that they can be reused easily in future projects.</p>

<h2 id="creating-module">1. Creating Module <a class="anchor" href="#creating-module">¶</a></h2>

<p>A module is organized as a directory whose name serves as its unique <a href="/doc/api/1.1/CWebModule#id">ID</a>. The structure of the module directory is similar to that of the <a href="/doc/guide/1.1/en/basics.application#application-base-directory">application base directory</a>. The following shows the typical directory structure of a module named <code>forum</code>:</p>

<pre>forum/
   ForumModule.php            the module class file
   components/                containing reusable user components
      views/                  containing view files for widgets
   controllers/               containing controller class files
      DefaultController.php   the default controller class file
   extensions/                containing third-party extensions
   models/                    containing model class files
   views/                     containing controller view and layout files
      layouts/                containing layout view files
      default/                containing view files for DefaultController
         index.php            the index view file
</pre>

<p>A module must have a module class that extends from <a href="/doc/api/1.1/CWebModule">CWebModule</a>. The class name is determined using the expression <code>ucfirst($id).'Module'</code>, where <code>$id</code> refers to the module ID (or the module directory name). The module class serves as the central place for storing information shared among the module code. For example, we can use <a href="/doc/api/1.1/CWebModule#params">CWebModule::params</a> to store module parameters, and use <a href="/doc/api/1.1/CWebModule#components">CWebModule::components</a> to share <a href="/doc/guide/1.1/en/basics.application#application-component">application components</a> at the module level.</p>

<blockquote class="tip">
<p><strong>Tip:</strong> We can use the module generator in Gii to create the basic skeleton of a new module.</p>
</blockquote>

<h2 id="using-module">2. Using Module <a class="anchor" href="#using-module">¶</a></h2>

<p>To use a module, first place the module directory under <code>modules</code> of the <a href="/doc/guide/1.1/en/basics.application#application-base-directory">application base directory</a>. Then declare the module ID in the <a href="/doc/api/1.1/CWebApplication#modules">modules</a> property of the application. For example, in order to use the above <code>forum</code> module, we can use the following <a href="/doc/guide/1.1/en/basics.application#application-configuration">application configuration</a>:</p>

<div class="hl-code"><div class="hl-main"><pre><span class="hl-reserved">return</span> <span class="hl-reserved">array</span><span class="hl-brackets">(</span><span class="hl-code">
    ......
    </span><span class="hl-quotes">'</span><span class="hl-string">modules</span><span class="hl-quotes">'</span><span class="hl-code">=&gt;</span><span class="hl-reserved">array</span><span class="hl-brackets">(</span><span class="hl-quotes">'</span><span class="hl-string">forum</span><span class="hl-quotes">'</span><span class="hl-code">,...</span><span class="hl-brackets">)</span><span class="hl-code">,
    ......
</span><span class="hl-brackets">)</span><span class="hl-code">;</span></pre></div></div>

<p>A module can also be configured with initial property values. The usage is very similar to configuring <a href="/doc/guide/1.1/en/basics.application#application-component">application components</a>. For example, the <code>forum</code> module may have a property named <code>postPerPage</code> in its module class which can be configured in the <a href="/doc/guide/1.1/en/basics.application#application-configuration">application configuration</a> as follows:</p>

<div class="hl-code"><div class="hl-main"><pre><span class="hl-reserved">return</span> <span class="hl-reserved">array</span><span class="hl-brackets">(</span><span class="hl-code">
    ......
    </span><span class="hl-quotes">'</span><span class="hl-string">modules</span><span class="hl-quotes">'</span><span class="hl-code">=&gt;</span><span class="hl-reserved">array</span><span class="hl-brackets">(</span>
        <span class="hl-quotes">'</span><span class="hl-string">forum</span><span class="hl-quotes">'</span><span class="hl-code">=&gt;</span><span class="hl-reserved">array</span><span class="hl-brackets">(</span>
            <span class="hl-quotes">'</span><span class="hl-string">postPerPage</span><span class="hl-quotes">'</span><span class="hl-code">=&gt;</span><span class="hl-number">20</span><span class="hl-code">,
        </span><span class="hl-brackets">)</span><span class="hl-code">,
    </span><span class="hl-brackets">)</span><span class="hl-code">,
    ......
</span><span class="hl-brackets">)</span><span class="hl-code">;</span></pre></div></div>

<p>The module instance may be accessed via the <a href="/doc/api/1.1/CController#module">module</a> property of the currently active controller. Through the module instance, we can then access information that are shared at the module level. For example, in order to access the above <code>postPerPage</code> information, we can use the following expression:</p>

<div class="hl-code"><div class="hl-main"><pre><span class="hl-var">$postPerPage</span><span class="hl-code">=</span><span class="hl-identifier">Yii</span><span class="hl-code">::</span><span class="hl-identifier">app</span><span class="hl-brackets">(</span><span class="hl-brackets">)</span><span class="hl-code">-&gt;</span><span class="hl-identifier">controller</span><span class="hl-code">-&gt;</span><span class="hl-identifier">module</span><span class="hl-code">-&gt;</span><span class="hl-identifier">postPerPage</span><span class="hl-code">;
</span><span class="hl-comment">//</span><span class="hl-comment"> or the following if $this refers to the controller instance</span>
<span class="hl-comment">//</span><span class="hl-comment"> $postPerPage=$this-&gt;module-&gt;postPerPage;</span></pre></div></div>

<p>A controller action in a module can be accessed using the <a href="/doc/guide/1.1/en/basics.controller#route">route</a> <code>moduleID/controllerID/actionID</code>. For example, assuming the above <code>forum</code> module has a controller named <code>PostController</code>, we can use the <a href="/doc/guide/1.1/en/basics.controller#route">route</a> <code>forum/post/create</code> to refer to the <code>create</code> action in this controller. The corresponding URL for this route would be <code>http://www.example.com/index.php?r=forum/post/create</code>.</p>

<blockquote class="tip">
<p><strong>Tip:</strong> If a controller is in a sub-directory of <code>controllers</code>, we can still use the above <a href="/doc/guide/1.1/en/basics.controller#route">route</a> format. For example, assuming <code>PostController</code> is under <code>forum/controllers/admin</code>, we can refer to the <code>create</code> action using <code>forum/admin/post/create</code>.</p>
</blockquote>

<h2 id="nested-module">3. Nested Module <a class="anchor" href="#nested-module">¶</a></h2>

<p>Modules can be nested in unlimited levels. That is, a module can contain another module which can contain yet another module. We call the former <em>parent module</em> while the latter <em>child module</em>. Child modules must be declared in the <a href="/doc/api/1.1/CWebModule#modules">modules</a> property of their parent module, like we declare modules in the application configuration shown as above.</p>

<p>To access a controller action in a child module, we should use the route <code>parentModuleID/childModuleID/controllerID/actionID</code>.</p>

<div class="revision"><div class="google-ad" style="margin:-60px 0 5px 200px;">
<script type="text/javascript"><!--
google_ad_client = "ca-pub-3732587985864947";
google_ad_slot = "7116172008";
google_ad_width = 300;
google_ad_height = 250;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</div>$Id$</div>
</div>
                <div class="prev-next-nav">
                            <div class="prev-topic"><a href="/doc/guide/1.1/en/basics.component">Component</a></div>
                                        <div class="next-topic"><a href="/doc/guide/1.1/en/basics.namespace">Path Alias and Namespace</a></div>
                    </div>
        
		        <div class="widget-comment-list" id="comments">
	<div class="comments">
		<h3>Total 6 comments</h3>
				<div class="comment alt-0">
			<a class="cid" id="c9890" title="permalink to this comment" href="#c9890">#9890</a>
			<a class="widget-reporter" title="Please report to us if you find any inappropriate content." href="/site/report/?type=Comment&amp;id=9890"><span>report it</span></a>			<div class="widget-voter"><ul>
	<li class="vote up"><a title="Thumb up" class="g-login" href="/site/vote/?type=Comment&amp;id=9890&amp;vote=1"><span>7</span></a></li>
	<li class="vote down"><a title="Thumb down" class="g-login" href="/site/vote/?type=Comment&amp;id=9890&amp;vote=0"><span>1</span></a></li>
</ul>
<div class="clear"></div></div>			<div class="meta"><a class="g-user-rank-link" href="/user/5292/">flarpy</a> at 2012/09/19 09:16am</div>
			<div class="title">Access to other modules</div>
			<div class="content"><p>To access a different module or a model within a different module, use</p>

<div class="hl-code"><div class="hl-main"><pre><span class="hl-identifier">Yii</span><span class="hl-code">::</span><span class="hl-identifier">app</span><span class="hl-brackets">(</span><span class="hl-brackets">)</span><span class="hl-code">-&gt;</span><span class="hl-identifier">getModule</span><span class="hl-brackets">(</span><span class="hl-quotes">'</span><span class="hl-string">moduleName</span><span class="hl-quotes">'</span><span class="hl-brackets">)</span><span class="hl-code">;</span></pre></div></div>

<p>You can then use models from that module in the usual way.</p>
</div>
					</div>
				<div class="comment alt-1">
			<a class="cid" id="c8820" title="permalink to this comment" href="#c8820">#8820</a>
			<a class="widget-reporter" title="Please report to us if you find any inappropriate content." href="/site/report/?type=Comment&amp;id=8820"><span>report it</span></a>			<div class="widget-voter"><ul>
	<li class="vote up"><a title="Thumb up" class="g-login" href="/site/vote/?type=Comment&amp;id=8820&amp;vote=1"><span>2</span></a></li>
	<li class="vote down"><a title="Thumb down" class="g-login" href="/site/vote/?type=Comment&amp;id=8820&amp;vote=0"><span>0</span></a></li>
</ul>
<div class="clear"></div></div>			<div class="meta"><a class="g-user-rank-link" href="/user/2096/">yugene</a> at 2012/06/30 01:14am</div>
			<div class="title">Case sensitivity</div>
			<div class="content"><p>Please notice, when using module that contains uppercase characters in its name, if you have caseSensitive parameter of urlManager set to false</p>

<div class="hl-code"><div class="hl-main"><pre><span class="hl-quotes">'</span><span class="hl-string">urlManager</span><span class="hl-quotes">'</span><span class="hl-code"> =&gt; </span><span class="hl-reserved">array</span><span class="hl-brackets">(</span>
            <span class="hl-quotes">'</span><span class="hl-string">caseSensitive</span><span class="hl-quotes">'</span><span class="hl-code"> =&gt; </span><span class="hl-reserved">false</span><span class="hl-code">,
</span><span class="hl-brackets">)</span></pre></div></div>

<p>then you won't be able to reach this module, getting Error 404 (Page not found).
So you have whether to rename your module to have lowercase name or set 'caseSensitive' parameter to TRUE.</p>

<p>This is an expected behavior, please read <a href="http://www.yiiframework.com/doc/api/1.1/CUrlManager#caseSensitive-detail" title="documentation">documentation</a></p>
</div>
					</div>
				<div class="comment alt-0">
			<a class="cid" id="c5100" title="permalink to this comment" href="#c5100">#5100</a>
			<a class="widget-reporter" title="Please report to us if you find any inappropriate content." href="/site/report/?type=Comment&amp;id=5100"><span>report it</span></a>			<div class="widget-voter"><ul>
	<li class="vote up"><a title="Thumb up" class="g-login" href="/site/vote/?type=Comment&amp;id=5100&amp;vote=1"><span>4</span></a></li>
	<li class="vote down"><a title="Thumb down" class="g-login" href="/site/vote/?type=Comment&amp;id=5100&amp;vote=0"><span>0</span></a></li>
</ul>
<div class="clear"></div></div>			<div class="meta"><a class="g-user-rank-link" href="/user/13312/">Jose Rullan</a> at 2011/09/14 12:31pm</div>
			<div class="title">How to access the Module from within its views and controllers</div>
			<div class="content"><p>The modules can be accessed through the CController property "module" - it returns the CWebModule to which the controller belongs. So for example if you want to know the base path of a module from within its controller or view, you can do it like this:</p>

<div class="hl-code"><div class="hl-main"><pre><span class="hl-var">$myPath</span><span class="hl-code"> = </span><span class="hl-var">$this</span><span class="hl-code">-&gt;</span><span class="hl-identifier">module</span><span class="hl-code">-&gt;</span><span class="hl-identifier">basePath</span><span class="hl-code">;</span></pre></div></div>
</div>
					</div>
				<div class="comment alt-1">
			<a class="cid" id="c3707" title="permalink to this comment" href="#c3707">#3707</a>
			<a class="widget-reporter" title="Please report to us if you find any inappropriate content." href="/site/report/?type=Comment&amp;id=3707"><span>report it</span></a>			<div class="widget-voter"><ul>
	<li class="vote up"><a title="Thumb up" class="g-login" href="/site/vote/?type=Comment&amp;id=3707&amp;vote=1"><span>7</span></a></li>
	<li class="vote down"><a title="Thumb down" class="g-login" href="/site/vote/?type=Comment&amp;id=3707&amp;vote=0"><span>0</span></a></li>
</ul>
<div class="clear"></div></div>			<div class="meta"><a class="g-user-rank-link bronze" href="/user/6843/">marcovtwout</a> at 2011/04/29 10:28am</div>
			<div class="title">Alias ... is invalid</div>
			<div class="content"><p>Note the case sensitive paths in Linux. Yii's preferred version is <em>module name in lowercase.</em></p>

<p>I created my own module 'application/modules/Page/', developing on a Windows machine.
When running the application on a Linux machine, I received the following error <em>"Alias "page.PageModule" is invalid. Make sure it points to an existing PHP file."</em>. Renaming the module directory to 'page' fixed the problem.</p>
</div>
					</div>
				<div class="comment alt-0">
			<a class="cid" id="c2234" title="permalink to this comment" href="#c2234">#2234</a>
			<a class="widget-reporter" title="Please report to us if you find any inappropriate content." href="/site/report/?type=Comment&amp;id=2234"><span>report it</span></a>			<div class="widget-voter"><ul>
	<li class="vote up"><a title="Thumb up" class="g-login" href="/site/vote/?type=Comment&amp;id=2234&amp;vote=1"><span>3</span></a></li>
	<li class="vote down"><a title="Thumb down" class="g-login" href="/site/vote/?type=Comment&amp;id=2234&amp;vote=0"><span>0</span></a></li>
</ul>
<div class="clear"></div></div>			<div class="meta"><a class="g-user-rank-link silver" href="/user/7141/">Trejder</a> at 2010/11/30 03:07am</div>
			<div class="title">Initial property values declaration!</div>
			<div class="content"><p>To make example with initial property values (see "2. Using Module") work, you must remember that property you are setting this way <strong>must be declared</strong> in module main file!</p>

<p>I.e. If you are building module <em>forum</em> and want to be able to setup <em>postPerPage</em> property (as in the example), you have to edit <em>protected/modules/forum/ForumModule.php</em> and add in the beginning following code:</p>

<div class="hl-code"><div class="hl-main"><pre><span class="hl-reserved">class</span> <span class="hl-identifier">UserModule</span> <span class="hl-reserved">extends</span> <span class="hl-identifier">CWebModule</span>
<span class="hl-brackets">{</span>
    <span class="hl-reserved">public</span> <span class="hl-var">$postPerPage</span><span class="hl-code"> = </span><span class="hl-number">20</span><span class="hl-code">;
    ...
</span><span class="hl-brackets">}</span></pre></div></div>

<p>where <strong>20</strong> is a default value for this property, in case user would not specify one in module configuration.</p>

<p>Without this you will see <em>error 500</em> saying that property <em>ForumModule.postPerPage</em> is an undefined.</p>
</div>
					</div>
				<div class="comment alt-1">
			<a class="cid" id="c1746" title="permalink to this comment" href="#c1746">#1746</a>
			<a class="widget-reporter" title="Please report to us if you find any inappropriate content." href="/site/report/?type=Comment&amp;id=1746"><span>report it</span></a>			<div class="widget-voter"><ul>
	<li class="vote up"><a title="Thumb up" class="g-login" href="/site/vote/?type=Comment&amp;id=1746&amp;vote=1"><span>10</span></a></li>
	<li class="vote down"><a title="Thumb down" class="g-login" href="/site/vote/?type=Comment&amp;id=1746&amp;vote=0"><span>0</span></a></li>
</ul>
<div class="clear"></div></div>			<div class="meta"><a class="g-user-rank-link" href="/user/1025/">MasterAM</a> at 2009/04/19 05:58am</div>
			<div class="title">Setting nested modules</div>
			<div class="content"><p>I did the following in order to nest modules:</p>

<p></p><pre><code>'modules'=&gt;array(
    'module1'=&gt;array(
        'modules'=&gt;array(
            'module2',
            'module3'
        )
    )
)
</code></pre>
Where modules 2 and 3 are nested within module 1
</div>
					</div>
			</div>
	<div id="comment-add">
		<h3 id="add-comment">Leave a comment</h3>

			<p>Please <a class="g-login" rel="/doc/guide/1.1/en/basics.module#add-comment" href="#">login</a> to leave your comment.</p>
		</div>
</div>
           </div>
</div>
					</div>
				
								<div class="clear"></div>
			</div>
			<div class="clear"></div>
					</div>
	</div>

	<div class="layout-main-footer">
		<div class="container_12">
			<div class="grid_6">
				<ul class="menu">
				<li class="main">About
<ul class="sub">
<li><a href="/about/">About Yii</a></li>
<li><a href="/features/">Features</a></li>
<li><a href="/performance/">Performance</a></li>
<li><a href="/license/">License</a></li>
<li><a href="/contact/">Contact Us</a></li>
</ul>
</li>
<li class="main">Downloads
<ul class="sub">
<li><a href="/download/">Framework</a></li>
<li><a href="/extensions/">Extensions</a></li>
<li><a href="/demos/">Demos</a></li>
<li><a href="/logo/">Logo</a></li>
</ul>
</li>
<li class="main">Documentation
<ul class="sub">
<li><a href="/tour/">Take the Tour</a></li>
<li><a href="/tutorials/">Tutorials</a></li>
<li><a href="/doc/api/">Class Reference</a></li>
<li><a href="/doc-2.0/guide-index.html">Guide 2.0</a></li>
<li><a href="/doc-2.0/index.html">Class Reference 2.0</a></li>
<li><a href="/wiki/">Wiki</a></li>
<li><a href="/screencasts/">Screencasts</a></li>
<li><a href="/resources/">Resources</a></li>
</ul>
</li>
<li class="main">Development
<ul class="sub">
<li><a href="/contribute/">Contribute to Yii</a></li>
<li><a href="https://github.com/yiisoft/yii/commits/master">Latest Updates</a></li>
<li><a href="https://github.com/yiisoft/yii/issues/new">Report a Bug</a></li>
<li><a href="/security/">Report a Security Issue</a></li>
</ul>
</li>
<li class="main">Community
<ul class="sub">
<li><a href="/forum/">Forum</a></li>
<li><a href="/chat/">Live Chat</a></li>
<li><a href="/news/">News</a></li>
<li><a href="/user/halloffame/">Hall of Fame</a></li>
<li><a href="/badges/">Badges</a></li>
</ul>
</li>
				</ul>
			</div>
			<div class="grid_1">&nbsp;</div>
			<div class="grid_5">
				<h3>Yii Supporters</h3>
				<ul class="g-list-none supporters">

				</ul>
			</div>

			<div class="clear"></div>
			<div class="grid_12 copyright">
				<ul class="social">
					<li class="twitter"><a href="https://twitter.com/yiiframework" target="_blank" rel="nofollow" title="follow us on twitter">Twitter</a></li>
					<li class="facebook"><a href="https://www.facebook.com/groups/yiitalk/" target="_blank" rel="nofollow" title="join yii group at facebook">Facebook</a></li>
					<li class="linkedin"><a href="http://www.linkedin.com/groups?gid=1483367" target="_blank" rel="nofollow" title="join yii group at linkedin">LinkedIn</a></li>
					<li class="feeds"><a title="RSS feeds" href="/rss.xml/">RSS Feeds</a></li>
				</ul>
				<div class="clear"></div>
				<a href="/tos/">Terms of Service</a> |
				<a href="/license/">License</a> |
				<a href="/contact/">Contact Us</a><br/>
				Copyright &copy; 2015 by <a href="http://www.yiisoft.com">Yii Software LLC</a>.
				All Rights Reserved.
			</div>
			<div class="clear"></div>
		</div>
	</div>
</div>

    <script type="text/javascript" src="/js/site-20121004195728.js"></script>


<script type="text/javascript">
var _gaq = _gaq || [];
_gaq.push(['site._setAccount', 'UA-5843896-1']);
_gaq.push(['site._trackPageview']);

(function() {
	var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
</script>
<script type="text/javascript">
function trackClick(link, action, category) {
	action=action || link.href;
	category=category || 'Outbound Links';
	try {
		_gaq.push(['site._trackEvent', category, action]);
		setTimeout('document.location = "' + link.href + '"', 250);
	}catch(err){}
	return false;
}
</script>
<script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>
</body>
</html>
