<div class="modal fade" id="addrepay">
	<div class="modal-dialog modal-small">
		<div class="modal-content">
			<div class="modal-header">
				<h5>添加还款记录</h5>
			</div>
			<div class="modal-body">

<form action="/afterloan/addrepay" method="post" class="form-horizontal">
	<input type="hidden" name="uid" value="<?=$detail['uid']?>">
	<input type="hidden" name="lid" value="<?=$detail['lid']?>">
	<div class="form-group">
		<label class="col-lg-2 control-label">客户编号</label>
		<div class="col-lg-8">
			<label class="control-label"><?=$detail['uid']?></label>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">还款金额</label>
		<div class="col-lg-4">
			<div class="input-group">
				<?=\Util\Html::input('amount', ['class'=>'{required:1, number:1}'])?>
				<span class="input-group-addon">元</span>
			</div>
		</div>
		<div class="col-lg-4 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">第几期</label>
		<div class="col-lg-4">
			<div class="input-group">
				<?=\Util\Html::select('no', \Func\remainDeadlines($detail['deadline'], $detail['return_no']))?>
				<span class="input-group-addon">期</span>
			</div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">还款状态</label>
		<div class="col-lg-4">
			<div class="radio"><?=\Util\Html::radio('status', [1=>'正常还款', 0=>'已逾期'], 1)?></div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">还款日期</label>
		<div class="col-lg-4">
			<?=\Util\Html::input('date', ['class'=>"{date:1}"], date('Y-m-d'))?>
		</div>
		<div class="col-lg-2 remark"><div class="row">格式：<?=date('Y-m-d')?></div></div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label"></label>
		<div class="col-lg-6">
			<button type="submit" class="btn btn-primary">提交</button>
		</div>
	</div>
</form>

			</div>
			<div class="modal-footer"></div>
		</div>
	</div>
</div>
