<div class="panel panel-default department_list">
	<div class="panel-heading">部门管理
		<a href="/adm/department/add" class="pull-right">添加部门</a>
	</div>
	<div class="panel-body">
<?php if (count($departments)): ?>
		<table class="table table-striped">
			<tr>
				<th>ID</th>
				<th>部门名称</th>
				<th>操作</th>
			</tr>
<?php foreach ($departments as $key=>$row): ?>
			<tr>
				<td><?=$row['did']?></td>
				<td><?=$row['name']?></td>
				<td></td>
			</tr>
<?php endforeach; ?>
		</table>
<?php else: ?>
		<div class="empty empty-content text-center">
			没有数据
		</div>
<?php endif; ?>
	</div>
</div>
