<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8"/>
	<link rel="stylesheet" href="/public/css/lib/bootstrap.min.css">
	<link rel="stylesheet" href="/public/css/site.css">
	<title><?= empty($heads['title']) ? '' : $heads['title'] . ' - ';?> 贷款系统</title>
</head>
<body>
<div class="view">
<!--/ header -->
	<?= $this->partial('common/header') ?>
	<div class="row content">
		<div class="col-lg-1"></div>
		<div class="col-lg-10">
		<?= $this->getContent() ?>
		</div>
	</div>
<!--/ footer-->
	<?= $this->partial('common/footer') ?>
</div>
<?php
if (isset($bodyPartial)):
	if (is_string($bodyPartial)):
		$this->partial($bodyPartial);
	elseif (is_array($bodyPartial)):
		$this->partial($bodyPartial[0], $bodyPartial[1]);
	endif;
endif;

\Assert\app();
\Assert\output(null, true);
?>
</body>
</html>
