<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8"/>
	<link rel="stylesheet" href="/public/css/lib/bootstrap.min.css">
	<link rel="stylesheet" href="/public/css/site.css">
	<title><?= empty($heads['title']) ? '' : $heads['title'] . ' - ';?> 贷款系统</title>
</head>
<body>
<div class="view">
<!--/ header -->
	<?= $this->partial('common/header') ?>
	<div class="content">
		<div class="col-lg-1"></div>
		<div class="col-lg-10">
		<?= $this->getContent() ?>
		</div>
	</div>
<!--/ footer-->
	<?= $this->partial('common/footer') ?>
</div>
</body>
</html>
