<?php
function outputLi($text, $value)
{
	echo "<li><label>$text</label><span class='value'>$value</span></li>";
}
?>

<div class="detailInfo">
	<h5>客户信息</h5>
	<hr/>
	<div>
	<ul>
<?=outputLi('客户姓名', $detailInfo['realname'])?>
<?=outputLi('联系方式', $detailInfo['mobile'])?>
<?=outputLi('身份证号', $detailInfo['idcard'])?>
	</ul>
	<div class="clear"></div>
	</div>
	<p>
		<label>居住地址</label>
		<span class="value">
			<span address-format="province"><?=$detailInfo['province']?></span>&nbsp;&nbsp;
			<span address-format="city" address-province="<?=$detailInfo['province']?>"><?=$detailInfo['city']?></span>&nbsp;&nbsp;
			<?=$detailInfo['address']?>
		</span>
	</p>
</div>
