<?php 
$form = new CarForm('assess', ['uid'=>$uid]);
?>
<div class="panel panel-default check">
	<div class="panel-heading">车评</div>
	<div class="panel-body">
		<?=$form->beginForm(['action'=>'/loan/car'])?>
		<input type="hidden" name="uid" value="<?=$uid?>">
	<div class="form-group">
		<label class="col-lg-2 control-label">贷款情况</label>
		<div class="col-lg-8">
			<div class="radio">
			<?=\Util\Html::radio('car_loan', \App\Config\Car::loan(), 1)?>
			</div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label"></label>
		<div class="col-lg-8">
			<div class="radio">
			<?=\Util\Html::radio('car_otherhand', \App\Config\Car::otherhand(), 1)?>
			</div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">二手车说明</label>
		<div class="col-lg-8">
			<?=\Util\Html::textarea('car_secondhand_info')?>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">汽车品牌-车系</label>
		<div class="col-lg-8">
			<div cascaded-data='car' cascaded-fields="car_brand#car_type"></div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">购买价格</label>
		<div class="col-lg-3">
			<div class="input-group">	
			<?=\Util\Html::input('car_price', ['class'=>'{required:1, min:0}'])?>	
			<span class="input-group-addon">万元</span>
			</div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">购买时间</label>
		<div class="col-lg-3">
			<?=\Util\Html::input('car_buytime', ['class'=>"{required:1, regex:'^[\\\\d]{4}-[\\\\d]{1,2}-[\\\\d]{1,2}$'}"])?>
		</div>
		<div class="col-lg-2 remark">格式：2013-10-10</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">汽车外观</label>
		<div class="col-lg-8">
			<div class="radio">
			<?=\Util\Html::radio('car_appearance', \App\Config\Car::appearance(), 0)?>
			</div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">汽车内观</label>
		<div class="col-lg-8">
			<div class="radio">
			<?=\Util\Html::radio('car_inappearance', \App\Config\Car::inappearance(), 0)?>
			</div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">事故说明</label>
		<div class="col-lg-8">
			<?=\Util\Html::textarea('car_accident_info')?>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">每月掉价幅度</label>
		<div class="col-lg-3">
			<div class="input-group">	
			<?=\Util\Html::input('car_fall_price', ['type'=>'number', 'class'=>''])?>	
			<span class="input-group-addon">元</span>
			</div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">评估价格</label>
		<div class="col-lg-3">
			<div class="input-group">	
			<?=\Util\Html::input('car_assess_price', ['class'=>'{min:0}'])?>	
			<span class="input-group-addon">万元</span>
			</div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">其它说明</label>
		<div class="col-lg-8">
			<?=\Util\Html::textarea('car_remark', ['class'=>''])?>	
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label"></label>
		<div class="col-lg-8">
			<button type="submit" class="btn btn-primary">提交</button>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>

		<?=$form->endForm()?>
	</div>
</div>
<?php \Func\loadJsFile(null, ['depends'=>'\Assert\validate'])?>
<?php \Func\loadJsFile(null, ['depends'=>'\Assert\cars'], APP_NAME)?>
