<?php 
$form = new CarForm('assess', ['uid'=>$uid]);
?>
<div class="panel panel-default check">
	<div class="panel-heading">车评</div>
	<div class="panel-body">
		<?=$form->beginForm(['action'=>'/loan/car/'.$uid])?>
		<input type="hidden" name="uid" value="<?=$uid?>">
	<h6>车主信息</h6>	
	<hr>
	<div class="form-group">
		<label class="col-lg-2 control-label">车主</label>
		<div class="col-lg-3">
			<?=\Util\Html::input('car_owner',['class'=>'{required:1}'], $user['realname'])?>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">联系电话</label>
		<div class="col-lg-3">
			<?=\Util\Html::input('mobile',['class'=>'{required:1}'], $user['mobile'])?>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">居住地址</label>
		<div class="col-lg-8">
			<?=\Util\Html::input('home_address',['class'=>'{required:1}'], $user['address'])?>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<br/>
	<h6>原始情况</h6>	
	<hr>
	<div class="form-group">
		<label class="col-lg-2 control-label">照片</label>
		<div class="col-lg-8">
		<a href="/loan/upload/car/<?=$user['uid']?>" class="input-text">上传</a>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">所有性质</label>
		<div class="col-lg-8">
			<div class="radio">
			<?=\Util\Html::radio('car_nature', \App\Config\Car::carNature(), isset($car['car_nature']) ? $car['car_nature'] : 1)?>
			</div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">汽车品牌-车系</label>
		<div class="col-lg-8">
		<div cascaded-data='car' cascaded-fields="car_brand#car_type"></div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">牌照</label>
		<div class="col-lg-3">
			<?=\Util\Html::input('car_number',['class'=>'{required:1}'], $car['car_number'])?>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">车身颜色</label>
		<div class="col-lg-3">
			<?=\Util\Html::input('car_color', null, $car['car_color'])?>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">车辆识别代码（VIN）</label>
		<div class="col-lg-3">
			<?=\Util\Html::input('car_vin',['class'=>'{required:1}'], $car['car_vin'])?>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">发动机号</label>
		<div class="col-lg-3">
			<?=\Util\Html::input('car_engine_number',null,$car['car_engine_number'])?>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">坐位/排量</label>
		<div class="col-lg-3">
			<?=\Util\Html::input('car_seat_count',['class'=>'{required:1}'], $car['car_seat_count'])?>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">初次登记日期</label>
		<div class="col-lg-3">
			<?=\Util\Html::input('car_register_date', ['class'=>"{date:1}"], date('Y-m-d',$car['car_register_date']))?>
		</div>
		<div class="col-lg-2 remark">格式：<?=date('Y-m-d')?></div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">累计行驶里程</label>
		<div class="col-lg-3">
			<div class="input-group">
			<?=\Util\Html::input('car_mileage', ['class'=>'{required:1,number:1}'], $car['car_mileage'])?>
			<span class="input-group-addon">公里</span>
			</div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">已使用年限</label>
		<div class="col-lg-3">
			<div class="input-group">
			<?=\Util\Html::input('car_age',['class'=>'{required:1,number:1}'], $car['car_age'])?>
			<span class="input-group-addon">年</span>
			</div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">使用用途</label>
		<div class="col-lg-3">
			<?=\Util\Html::input('car_use',null,$car['car_use'])?>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<br/>
	<h6>检车核对交易证件</h6>	
	<hr>
	<div class="form-group">
		<label class="col-lg-2 control-label">证件</label>
		<div class="col-lg-8">
			<div class="checkbox">
			<label><?=\Util\Html::checkbox('car_bill', [1=>'原始发票'], $car['car_bill'])?></label>
			<label><?=\Util\Html::checkbox('car_register_license', [1=>'机动车登记证书'], $car['car_register_license'])?></label>
			<label><?=\Util\Html::checkbox('car_legal_idcard', [1=>'法人代码或身份证'], $car['car_legal_idcard'])?></label>
			<label><?=\Util\Html::checkbox('car_other_license', [1=>'其它证件'], $car['car_other_license'])?></label>
			</div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">税费</label>
		<div class="col-lg-8">
			<div class="checkbox">
			<label><?=\Util\Html::checkbox('car_tax_addition', [1=>'购置税附加税'], $car['car_tax_addition'])?></label>
			<label><?=\Util\Html::checkbox('car_tax_use', [1=>'车船使用税'], $car['car_tax_use'])?></label>
			<label><?=\Util\Html::checkbox('car_insure', [1=>'交强险'], $car['car_insure'])?></label>
			<label><?=\Util\Html::checkbox('car_other_tax', [1=>'车船使用税'], $car['car_other_tax'])?></label>
			</div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<br/>
	<h6>调整系数（取值）</h6>	
	<hr>
	<div class="form-group">
		<label class="col-lg-2 control-label">技术状况</label>
		<div class="col-lg-8">
			<div class="radio">
			<?=\Util\Html::radio('car_status_tech', \App\Config\Car::statusTech(), isset($car['car_status_tech']) ? $car['car_status_tech'] : 1)?>
			</div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">维修保养</label>
		<div class="col-lg-8">
			<div class="radio">
			<?=\Util\Html::radio('car_status_maintain', \App\Config\Car::statusMaintain(), isset($car['car_status_maintain']) ? $car['car_status_maintain'] : 1)?>
			</div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">制造质量</label>
		<div class="col-lg-8">
			<div class="radio">
			<?=\Util\Html::radio('car_make_quality', \App\Config\Car::makeQuality(), isset($car['car_make_quality']) ? $car['car_make_quality'] : 1)?>
			</div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">工作性质</label>
		<div class="col-lg-8">
			<div class="radio">
			<?=\Util\Html::radio('car_work_nature', \App\Config\Car::workNature(), isset($car['car_work_nature']) ? $car['car_work_nature'] : 1)?>
			</div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">工作条件</label>
		<div class="col-lg-8">
			<div class="radio">
			<?=\Util\Html::radio('car_work_status', \App\Config\Car::workStatus(), isset($car['car_work_status']) ? $car['car_work_status'] : 1)?>
			</div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<br/>
	<h6>价值反映</h6>	
	<hr>
	<div class="form-group">
		<label class="col-lg-2 control-label">贷款情况</label>
		<div class="col-lg-8">
			<div class="radio">
			<?=\Util\Html::radio('car_loan', \App\Config\Car::loan(), isset($car['car_loan']) ? $car['car_loan'] : 1)?>
			</div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">贷款情况说明</label>
		<div class="col-lg-8">
			<?=\Util\Html::textarea('car_loan_info', null, $car['car_loan_info'])?>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">购买价格</label>
		<div class="col-lg-3">
			<div class="input-group">	
			<?=\Util\Html::input('car_price', ['class'=>'{required:1, min:0}'], $car['car_price'])?>	
			<span class="input-group-addon">万元</span>
			</div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">现价</label>
		<div class="col-lg-3">
			<div class="input-group">	
			<?=\Util\Html::input('car_price_now', ['class'=>'{required:1, min:0}'], $car['car_price_now'])?>	
			<span class="input-group-addon">万元</span>
			</div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">每月掉价幅度</label>
		<div class="col-lg-3">
			<div class="input-group">	
			<?=\Util\Html::input('car_fall_price', ['type'=>'number', 'class'=>''], $car['car_fall_price'])?>	
			<span class="input-group-addon">元</span>
			</div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">重置成本</label>
		<div class="col-lg-3">
			<div class="input-group">	
			<?=\Util\Html::input('car_reset_capital', ['type'=>'number', 'class'=>''], $car['car_reset_capital'])?>	
			<span class="input-group-addon">万元</span>
			</div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">成新率</label>
		<div class="col-lg-3">
			<div class="input-group">
			<?=\Util\Html::input('car_new_rate', ['class'=>'{number:1}'], $car['car_new_rate'])?>	
			<span class="input-group-addon">成新</span>
			</div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">评估价格</label>
		<div class="col-lg-3">
			<div class="input-group">	
			<?=\Util\Html::input('car_assess_price', ['class'=>'{required:1,min:0}'], $car['car_assess_price'])?>	
			<span class="input-group-addon">万元</span>
			</div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">鉴定评估说明</label>
		<div class="col-lg-8">
			<?=\Util\Html::textarea('car_assess_remark', ['class'=>'{required:1}'], $car['car_assess_remark'])?>	
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label"></label>
		<div class="col-lg-8">
			<button type="submit" class="btn btn-primary">提交</button>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>

		<?=$form->endForm()?>
	</div>
</div>
