<div class="faceinfo">
<h5>面审信息<span class="pull-right"><?=date('Y/m/d', $faceinfo['addtime'])?></span></h5>
<hr/>
<table class="table">
	<tr>
		<td width=10%><label>信用报告说明</label></td>
		<td>
			<table class="table">
				<tr>
					<td width=15%></label>负债总额</label></td>
					<td><?=$faceinfo['debt_amount']?></td>
				</tr>
				<tr>
					<td width=15%></label>证明方式</label></td>
					<td><?=$faceinfo['debt_prove']?></td>
				</tr>
				<tr>
					<td width=15%></label>每月还款金额</label></td>
					<td><?=$faceinfo['debt_month_repay']?></td>
				</tr>
				<tr>
					<td width=15%></label>逾期情况说明</label></td>
					<td><?=$faceinfo['debt_info']?></td>
				</tr>
				<tr>
					<td width=15%></label>按揭车还款情况</label></td>
					<td><?=$faceinfo['debt_car_info']?></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td width=10%><label>基本情况说明</label></td>
		<td>
			<table class="table">
				<tr>
					<td width=15%></label>个人基本情况</label></td>
					<td><?=$faceinfo['info_base']?></td>
				</tr>
				<tr>
					<td width=15%></label>个人收入情况</label></td>
					<td><?=$faceinfo['info_income']?></td>
				</tr>
				<tr>
					<td width=15%></label>借款用途核实</label></td>
					<td><?=$faceinfo['use_info']?></td>
				</tr>
				<tr>
					<td width=15%></label>还款来源核实</label></td>
					<td><?=$faceinfo['repay_source']?></td>
				</tr>
			</table>
		</td>
	</tr>
</table>
</div>
