<div class="reface refaceinfo disabled">
<table class="table input-disable">
	<tr>
		<td width=10%><label>面审意见</label></td>
		<td>
			综合上述客户情况本次批准金额：<span class="underline"><?=$refaceinfo['amount']?>万元.</span>&nbsp;&nbsp;
			贷款期限：<span class="underline"><?=$refaceinfo['deadline']?>个月</span>
			年利率：<span class="underline"><?=$refaceinfo['apr']?>%</span>
			还款方式：<span class="underline"><?=\App\Config\Loan::repayMethod()[$refaceinfo['repay_method']]?></span>
			<br/>同意或拒绝放款理由：<span class="underline"><?=$refaceinfo['reason']?></span>
			<br/>可能存在风险说明：<span class="underline"><?=$refaceinfo['risk']?></span>
			<br/>贷后注意事项：<span class="underline"><?=$refaceinfo['notice']?></span>
			<br/>其它说明：<span class="underline"><?=$refaceinfo['remark']?></span>
		</td>
	</tr>
</table>
