<?php 
$form = new FaceForm('reface', ['uid'=>$uid]);
?>
<div class="panel panel-default reface">
	<div class="panel-heading">复审</div>
	<div class="panel-body">
		<?=$form->beginForm(['action'=>'/loan/reface'])?>
		<input type="hidden" name="uid" value="<?=$uid?>">
	<div class="form-group reface-loan">
		<label class="col-lg-2 control-label">审批意见</label>
		<div class="col-lg-8">
			<ul>
				<li>批准金额：<?=\Util\Html::input('amount', ['class'=>'input-underline {required:1}'], $detailInfo['amount'])?>万元</li>
				<li>期限：<?=\Util\Html::input('deadline', ['class'=>'input-underline {required:1, min:1, max:24}'], $detailInfo['deadline'])?>个月</li>
				<li>利率：<?=\Util\Html::input('apr', ['class'=>'input-underline {required:1}'], $detailInfo['apr'])?>%</li>
				<li><div class="radio">还款方式：<?=\Util\Html::radio('repay_method', \App\Config\Loan::repayMethod(), $detailInfo['repay_method'])?></div></li>
			</ul>
			<div class="clear"></div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">担保人情况说明</label>
		<div class="col-lg-8">
			<?=\Util\Html::textarea('guarantee')?>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group reface-inputs">
		<label class="col-lg-2 control-label">意见说明</label>
		<div class="col-lg-8">
			同意或者拒绝放款理由：<?=\Util\Html::input('reason', ['class'=>'input-underline {required:1}'])?>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group reface-inputs">
		<label class="col-lg-2 control-label"></label>
		<div class="col-lg-8">
			可能存在风险说明：<?=\Util\Html::input('risk', ['class'=>'input-underline {required:1}'])?>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group reface-inputs">
		<label class="col-lg-2 control-label"></label>
		<div class="col-lg-8">
			贷后注意事项说明：<?=\Util\Html::input('notice', ['class'=>'input-underline {required:1}'])?>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group reface-inputs">
		<label class="col-lg-2 control-label"></label>
		<div class="col-lg-8">
			其它说明：<?=\Util\Html::input('remark', ['class'=>'input-underline'])?>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label"></label>
		<div class="col-lg-8">
			<button type="submit" class="btn btn-primary">提交</button>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>

		<?=$form->endForm()?>
	</div>
</div>
<?php \Func\loadJsFile(null, ['depends'=>'\Assert\validate'])?>
