<div class="visitinfo">
<table class="table input-disable">
	<tr>
		<td width=10%><label>实地外访</label></td>
		<td>
			<table class="table">
				<tr>
					<td>外访公司地址：<?=$visitinfo['visit_company_address']?></td>
				</tr>
				<tr>
					<td>
				<div class="checkbox disabled">
				<?=\Util\Html::checkbox('license_company_address', [1=>'公司地址是否与证件一致'], $visitinfo['license_company_address'])?>
				<?=\Util\Html::checkbox('income_company_address', [1=>'公司地址与收入证明是否一致'], $visitinfo['income_company_address'])?>
				</div>
					</td>
				</tr>
				<tr>
					<td>
					<div class="radio disabled">
				开业状况：<?=\Util\Html::radio('company_status', \App\Config\Company::status(), $visitinfo['company_status'])?>
					</div>
					</td>
				</tr>
				<tr>
					<td>
						<table>
							<tr>
				<td width=100>经营状况：</td>
				<td>
				经营面积：<span class="underline"><?=$visitinfo['company_area']?>.</span>&nbsp;&nbsp;
				内部装饰：<span class="underline"><?=$visitinfo['company_decorate']?>.</span>&nbsp;&nbsp;
				所属行业：<span class="underline"><?=$visitinfo['company_industry']?>.</span>&nbsp;&nbsp;
				公司人数：<span class="underline"><?=$visitinfo['company_people_number']?>.</span>&nbsp;&nbsp;
				公司其它情况：<span class="underline"><?=$visitinfo['company_info']?>.</span>&nbsp;&nbsp;
				</td>
							</tr>
						</table>
					</td>
				</ul>
				</tr>
				<tr>
					<td>
						<table>
							<tr>
				<td width=150>借款人的职务和收入：</td>
				<td>
				入职年限：<span class="underline"><?=$visitinfo['job_year']?>.</span>&nbsp;&nbsp;
				现任职务：<span class="underline"><?=$visitinfo['job_duty']?>.</span>&nbsp;&nbsp;
				收入：<span class="underline"><?=$visitinfo['job_income']?>.</span>&nbsp;&nbsp;
				出资金额：<span class="underline"><?=$visitinfo['invest_amount']?>.</span>&nbsp;&nbsp;
				出资比率：<span class="underline"><?=$visitinfo['invest_rate']?>.</span>&nbsp;&nbsp;
				</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td>外访家庭地址：<?=$visitinfo['visit_address']?></td>
				</tr>
				<tr>
					<td>
				<div class="checkbox disabled">
				<?=\Util\Html::checkbox('house_live_address', [1=>'房产地址是否与居住地址一致'], $visitinfo['house_live_address'])?>
				<?=\Util\Html::checkbox('house_live_often', [1=>'居住房屋是否有常住痕迹'], $visitinfo['house_live_often'])?>
				</div>
				补充：<span class="underline"><?=$visitinfo['house_live_address_info']?>.</span>&nbsp;&nbsp;
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
</div>
