<?php 
$form = new CheckForm('visit', ['uid'=>$uid]);
?>
<div class="panel panel-default check">
	<div class="panel-heading">实地外访</div>
	<div class="panel-body">
		<?=$form->beginForm(['action'=>'/loan/visit'])?>
		<input type="hidden" name="uid" value="<?=$uid?>">
	<div class="form-group">
		<label class="col-lg-2 control-label">外访公司地址</label>
		<div class="col-lg-8">
			<?=\Util\Html::input('visit_company_address', ['class'=>'input-underline {required:1}'])?>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>

	<div class="form-group">
		<label class="col-lg-2 control-label"></label>
		<div class="col-lg-8">
			<div class="checkbox">
				<?=\Util\Html::checkbox('license_company_address', [1=>'公司地址是否与证件一致'])?>
				<?=\Util\Html::checkbox('income_company_address', [1=>'公司地址与收入证明是否一致'])?>
			</div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label">开业状况</label>
		<div class="col-lg-8">
			<div class="radio">
				<?=\Util\Html::radio('company_status', \App\Config\Company::status())?>
			</div>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group check-company">
		<label class="col-lg-2 control-label">经营状况</label>
		<div class="col-lg-8">
			<ul>
				<li>经营面积：<?=\Util\Html::input('company_area', ['class'=>'input-underline'])?></li>
				<li>内部装饰：<?=\Util\Html::input('company_decorate', ['class'=>'input-underline'])?></li>
				<li>所属行业：<?=\Util\Html::input('company_industry', ['class'=>'input-underline'])?></li>
				<li>公司人数：<?=\Util\Html::input('company_people_number', ['class'=>'input-underline'])?></li>
			</ul>
			<div class="clear"></div>
			<br/>
			<p>其它情况说明：<?=\Util\Html::input('company_info', ['class'=>'input-underline'])?></p>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group check-job">
		<label class="col-lg-2 control-label">职务和收入</label>
		<div class="col-lg-8">
			<ul>
				<li>入职年限：<?=\Util\Html::input('job_year', ['class'=>'input-underline'])?></li>
				<li>现任职务：<?=\Util\Html::input('job_duty', ['class'=>'input-underline'])?></li>
				<li>收入：<?=\Util\Html::input('job_income', ['class'=>'input-underline'])?></li>
				<li>出资金额：<?=\Util\Html::input('invest_amount', ['class'=>'input-underline'])?></li>
				<li>出资比率：<?=\Util\Html::input('invest_rate', ['class'=>'input-underline'])?></li>
			</ul>
			<div class="clear"></div>
			<br/>
			<p>公司名称：<?=\Util\Html::input('job_company', ['class'=>'input-underline'])?></p>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>

	<div class="form-group">
		<label class="col-lg-2 control-label">外访家庭地址</label>
		<div class="col-lg-8">
			<?=\Util\Html::input('visit_address', ['class'=>'input-underline {required:1}'])?>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group check-house">
		<label class="col-lg-2 control-label"></label>
		<div class="col-lg-8">
			<div class="checkbox">
				<?=\Util\Html::checkbox('house_live_address', [1=>'房产地址与居住地址一致'])?>
				<?=\Util\Html::checkbox('house_live_ofter', [1=>'居住房屋有常住痕迹'])?>
			</div>
			<br/>
			<p>补充：<?=\Util\Html::input('house_live_address_info', ['class'=>'input-underline'])?></p>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>
	<div class="form-group">
		<label class="col-lg-2 control-label"></label>
		<div class="col-lg-8">
			<button type="submit" class="btn btn-primary">提交</button>
		</div>
		<div class="col-lg-2 help-block"></div>
	</div>

		<?=$form->endForm()?>
	</div>
</div>
<?php \Func\loadJsFile(null, ['depends'=>'\Assert\validate'])?>
