<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8"/>
	<link rel="stylesheet" href="/public/css/lib/bootstrap.min.css">
	<link rel="stylesheet" href="/public/css/adm.css">
</head>
<body>
<div class="view">
<!--/ header -->
	<?= $this->partial('common/header') ?>
<!--/ sidebar -->
	<div class="col-lg-2 sidebar">
		<div class="row"><?= $this->partial('common/sidebar') ?></div>
	</div>
	<div class="col-lg-10 content">
		<div class="row"><?= $this->getContent() ?></div>
	</div>
</div>
</body>
</html>
