<?php
$heads['title'] = '客户列表';
?>

<div class="loan-list">
	<form class="search row" action="<?=\Func\url('/finance/list')?>" method="get">
		<div class="col-lg-2 hide">
			<?\Util\Html::select('bid', Branch::options(), null, $_REQUEST['bid'])?>
		</div>
		<div class="col-lg-2">
			<?=\Util\Html::select('deal', ['' => '全部', -1=>'未处理', 1=>'已处理'], null, $_REQUEST['deal'])?>
		</div>
		<div class="col-lg-3">
			<div class="input-group">
				<?=\Util\Html::input('keyword', ['placeholder'=>'请输入客户编号或姓名'], $_REQUEST['keyword'])?>
				<span class="input-group-addon btn-search">搜索</span>
			</div>
		</div>
		<div class="col-lg-1"><div class="row"><a class="btn btn-link" href="/finance/list">清除</a></div></div>
	</form>
	<br/>
<?php
if (!empty($list)):
?>
<table class="table table-striped">
	<tr>
		<th>客户编号</th>
		<th>客户姓名</th>
		<th>联系方式</th>
		<th>贷款方式</th>
		<th>贷款金额 (万)</th>
		<th>贷款期限</th>
		<th>还款方式</th>
		<th>合同签署</th>
		<th>GPS安装</th>
		<th>操作</th>
	</tr>
<?php
	foreach ($list as $row):
?>

	<tr>
		<td><?=$row['uid']?></td>
		<td><?=$row['realname']?></td>
		<td><?=$row['mobile']?></td>
		<td><?=$row['loan_type_text']?></td>
		<td><?=$row['amount']?></td>
		<td><?=$row['deadline'] . ($row['deadline'] == 'd' ? '天' : '个月')?></td>
		<td><?=$row['repay_method_text']?></td>
		<td><?=$row['contract_text']?></td>
		<td><?=$row['gps_text']?></td>
		<td>
			<a href="/finance/detail/<?=$row['uid']?>">详情</a>
		</td>
	</tr>

<?php
	endforeach;
?>
</table>	
<?php
		$this->partial('common/page', $page);
else:
?>
		<div class="empty empty-content text-center">
			没有数据
		</div>
<?php
endif;
?>

</div>
